/* Português – made from i18n/*.txt by i18n/build.py. Edit those files, not this one. */
I18N.add('pt', {
"Home": "Início",
"Customers": "Clientes",
"Agents": "Agentes",
"History": "Histórico",
"Settings": "Definições",
"Customer": "Cliente",
"Agent": "Agente",
"Save": "Guardar",
"Save All": "Guardar tudo",
"Save, Add Another": "Guardar e adicionar outro",
"Close": "Fechar",
"Cancel": "Cancelar",
"Delete": "Eliminar",
"Deleted": "Eliminado",
"Edit": "Editar",
"Back": "Voltar",
"Continue": "Continuar",
"Copy": "Copiar",
"Copied": "Copiado",
"Share": "Partilhar",
"Remove": "Remover",
"Remove row": "Remover linha",
"Restore": "Restaurar",
"Saved": "Guardado",
"Saved. Add the next one.": "Guardado. Adicione o seguinte.",
"Today": "Hoje",
"Yesterday": "Ontem",
"Other Date": "Outra data",
"Pick": "Escolher",
"Choose": "Escolher",
"All": "Tudo",
"All Time": "Sempre",
"Everything": "Tudo",
"Date": "Data",
"Time": "Hora",
"Time (Optional)": "Hora (opcional)",
"Details": "Detalhes",
"Description": "Descrição",
"Notes": "Notas",
"Note": "Nota",
"Amount": "Valor",
"Total": "Total",
"Status": "Estado",
"Email": "E-mail",
"Password": "Palavra-passe",
"Country": "País",
"Currency": "Moeda",
"Symbol": "Símbolo",
"Code": "Código",
"Language": "Idioma",
"Language saved": "Idioma guardado",
"Phone language": "Idioma do telemóvel",
"Message Language": "Idioma da mensagem",
"The app can be used in English, French or Portuguese. This choice is only for this phone. Reminder messages have their own language choice when you send them.": "A aplicação pode ser usada em inglês, francês ou português. Esta escolha é só para este telemóvel. As mensagens de lembrete têm a sua própria escolha de idioma quando as envia.",
"Welcome": "Bem-vindo",
"Welcome,": "Bem-vindo,",
"Welcome back,": "Bem-vindo de volta,",
"Sales": "Vendas",
"Sale": "Venda",
"New Sale": "Nova venda",
"Edit Sale": "Editar venda",
"Customer Paid": "Pagamento de cliente",
"Edit Payment": "Editar pagamento",
"Agent Entry": "Operação de agente",
"Agent Entries": "Operações de agentes",
"Agent entries": "Operações de agentes",
"New Agent Entry": "Nova operação de agente",
"Edit Agent Entry": "Editar operação de agente",
"Money Out": "Saídas de dinheiro",
"Edit Money Out": "Editar saída de dinheiro",
"Record Balances": "Registar saldos",
"Change Balances": "Alterar saldos",
"Record Balances Now": "Registar saldos agora",
"Send Reminder": "Enviar lembrete",
"Send reminder": "Enviar lembrete",
"Send a Reminder": "Enviar um lembrete",
"Data / Deposit": "Internet / Depósito",
"Wallet Exchange": "Câmbio de carteira",
"Payments": "Pagamentos",
"Expenses and Money Out": "Despesas e saídas de dinheiro",
"Referral Sales": "Vendas de angariadores",
"Referral sales": "Vendas de angariadores",
"Referral Agents": "Agentes angariadores",
"Commissions": "Comissões",
"Commission": "Comissão",
"Daily Cash Check": "Verificação diária de caixa",
"Monthly Balance Check": "Verificação mensal de saldos",
"Capital Portfolio": "Carteira de capital",
"Risk Check": "Verificação de risco",
"Risk check": "Verificação de risco",
"Risk": "Risco",
"Losses and Errors": "Perdas e erros",
"Sales and Customers": "Vendas e clientes",
"Agents and Partners": "Agentes e parceiros",
"Money": "Dinheiro",
"Every day, with filters": "Todos os dias, com filtros",
"Who might not pay": "Quem pode não pagar",
"On WhatsApp": "No WhatsApp",
"Float and deals": "Float e operações",
"Sales for other agents": "Vendas para outros agentes",
"Wallets and EVC": "Carteiras e EVC",
"Does your money balance?": "O seu dinheiro bate certo?",
"Month by month": "Mês a mês",
"Available and working capital": "Capital disponível e de exploração",
"Write-offs and mistakes": "Perdas e erros",
"Money received today": "Dinheiro recebido hoje",
"Entries today": "Operações de hoje",
"Ready when you are": "Pronto quando quiser",
"Tap New Sale to record your first sale. Everything you record shows up here.": "Toque em Nova venda para registar a sua primeira venda. Tudo o que registar aparece aqui.",
"To Collect": "A receber",
"To Pay": "A pagar",
"To collect": "A receber",
"To pay": "A pagar",
"To Collect from Customers": "A receber de clientes",
"To Collect from Agents": "A receber de agentes",
"Paid in Advance": "Pago adiantado",
"Used on their next purchases": "Usado nas próximas compras",
"Overdue Sales": "Vendas em atraso",
"Commission This Month": "Comissão deste mês",
"Losses This Month": "Perdas deste mês",
"Working Capital": "Capital de exploração",
"Tips": "Gorjetas",
"Tips (extra income)": "Gorjetas (rendimento extra)",
"Tips (inside payments)": "Gorjetas (incluídas nos pagamentos)",
"Tips to Hand Over": "Gorjetas a entregar",
"Tips Handed Over": "Gorjetas entregues",
"Risk alerts": "Alertas de risco",
"Open risk check": "Abrir verificação de risco",
"Billed": "Faturado",
"Paid": "Pago",
"Biggest amounts to collect": "Maiores valores a receber",
"Chase these first.": "Cobre estes primeiro.",
"Your customers": "Os seus clientes",
"Commission by wallet and EVC": "Comissão por carteira e EVC",
"Regular": "Regular",
"Irregular": "Irregular",
"Inactive (90+ days)": "Inativo (90+ dias)",
"Bad (high risk)": "Mau (risco elevado)",
"Do not give credit": "Não dar crédito",
"Outstanding": "Em dívida",
"Overdue": "Em atraso",
"Overpaid": "Pago a mais",
"Bad debt": "Dívida incobrável",
"Settled": "Liquidado",
"Balanced": "Certo",
"Missing": "Em falta",
"Extra": "A mais",
"First Record": "Primeiro registo",
"First record": "Primeiro registo",
"Needs balances": "Faltam saldos",
"No opening balances": "Sem saldos iniciais",
"Search name, phone, reference or details": "Procurar nome, telefone, referência ou detalhes",
"Search name or phone": "Procurar nome ou telefone",
"Search agent, number or reference": "Procurar agente, número ou referência",
"Search history": "Procurar no histórico",
"Search customers": "Procurar clientes",
"Search agents": "Procurar agentes",
"Payment Status": "Estado do pagamento",
"Not Fully Paid": "Não pago na totalidade",
"Paid or Overpaid": "Pago ou pago a mais",
"Paid Through": "Pago por",
"Pick Dates": "Escolher datas",
"From": "De",
"To": "Até",
"Agent defaulted": "Agente em incumprimento",
"Try a different search or filter.": "Tente outra pesquisa ou filtro.",
"Try a different search, day or filter.": "Tente outra pesquisa, dia ou filtro.",
"Customer WhatsApp / Phone": "WhatsApp / telefone do cliente",
"Customer Name": "Nome do cliente",
"Customer name": "Nome do cliente",
"Customer phone": "Telefone do cliente",
"Customer Phone": "Telefone do cliente",
"Country of this number": "País deste número",
"Date of This Sale": "Data da venda",
"Date They Paid": "Data do pagamento",
"Date of This Entry": "Data da operação",
"Date It Was Paid": "Data do pagamento",
"Date of These Balances": "Data destes saldos",
"Date for These Sales": "Data destas vendas",
"Date for These Entries": "Data destas operações",
"Time the Customer Did It": "Hora da venda",
"Time They Paid": "Hora do pagamento",
"Time of the Transaction": "Hora da operação",
"Optional. The app also saves the exact moment you recorded the sale.": "Opcional. A aplicação também guarda o momento exato em que registou a venda.",
"Optional. The app also saves the exact moment you recorded it.": "Opcional. A aplicação também guarda o momento exato em que o registou.",
"Tap the date of this transaction.": "Toque na data desta operação.",
"Exchange Type": "Tipo de câmbio",
"Bundle, Deposit or Details": "Pacote, depósito ou detalhes",
"Amount You Sent Out (Optional)": "Valor que enviou (opcional)",
"What you paid out to the customer. It keeps your balance checks accurate.": "O que pagou ao cliente. Mantém as verificações de saldos corretas.",
"How Was It Paid?": "Como foi pago?",
"How was it paid": "Como foi pago",
"Tap how this sale was paid.": "Toque em como esta venda foi paga.",
"Paid in Full": "Pago na totalidade",
"Part Paid": "Pago em parte",
"On Credit": "A crédito",
"Money received": "Dinheiro recebido",
"Some received": "Parte recebida",
"Nothing yet": "Nada ainda",
"Amount Received So Far": "Valor já recebido",
"Amount received so far": "Valor já recebido",
"Other (type your own)…": "Outro (escreva)…",
"Other, type your own": "Outro, escreva",
"Type it here": "Escreva aqui",
"Bank Name": "Nome do banco",
"What the Data or Airtime Cost You (Optional)": "Quanto lhe custou a internet ou o saldo (opcional)",
"Used in your balance checks.": "Usado nas suas verificações de saldos.",
"Tip on Top (Extra Income)": "Gorjeta extra (rendimento extra)",
"Tip Included in the Amount Received": "Gorjeta incluída no valor recebido",
"Tip to Hand Over (Not Your Income)": "Gorjeta a entregar (não é rendimento seu)",
"Number That Received the Data or Money (If Different)": "Número que recebeu a internet ou o dinheiro (se for outro)",
"Date Paid, Only If Paid Later": "Data do pagamento, só se pagou mais tarde",
"Saves how many days late they paid.": "Guarda quantos dias de atraso.",
"Reason for Write-Off": "Motivo da perda",
"Only if you will never collect it.": "Só se nunca vai receber.",
"More Details": "Mais detalhes",
"Several Sales? Record Them All at Once": "Várias vendas? Registe-as todas de uma vez",
"Several Entries? Record Them All at Once": "Várias operações? Registe-as todas de uma vez",
"Several Sales at Once": "Várias vendas de uma vez",
"Several Agent Entries at Once": "Várias operações de agentes de uma vez",
"Several Entries at Once": "Várias operações de uma vez",
"Record several sales at once": "Registar várias vendas de uma vez",
"Type several sales, then save them all at once. The date you choose goes on every row, and you can still change any row's date.": "Escreva várias vendas e guarde-as todas de uma vez. A data escolhida vai para todas as linhas, e pode mudar a data de qualquer linha.",
"Type several entries, then save them all at once. The date you choose goes on every row, and you can still change any row's date.": "Escreva várias operações e guarde-as todas de uma vez. A data escolhida vai para todas as linhas, e pode mudar a data de qualquer linha.",
"Paid Through, for All Rows": "Pago por, para todas as linhas",
"Exchange Type, for All Rows": "Tipo de câmbio, para todas as linhas",
"Same as above": "Igual ao de cima",
"Add Another Row": "Adicionar linha",
"Add a row": "Adicionar linha",
"Type at least one sale.": "Escreva pelo menos uma venda.",
"Type at least one entry.": "Escreva pelo menos uma operação.",
"Amount Paid": "Valor pago",
"Type the amount they paid.": "Escreva o valor que pagou.",
"Still to Pay Now": "Ainda por pagar agora",
"After This Payment": "Depois deste pagamento",
"New customer: this payment is recorded as credit they can use later.": "Cliente novo: este pagamento fica como crédito para usar mais tarde.",
"Agent Name": "Nome do agente",
"Agent name": "Nome do agente",
"Use the same name every time, even if the agent uses another number.": "Use sempre o mesmo nome, mesmo que o agente use outro número.",
"Transaction Type": "Tipo de operação",
"Transaction type": "Tipo de operação",
"For example: ComCach float, Xpress deposit, GT Bank to Wave.": "Por exemplo: float ComCach, depósito Xpress, GT Bank para Wave.",
"Paid to Agent": "Pago ao agente",
"Received from Agent": "Recebido do agente",
"Paid to agent": "Pago ao agente",
"Received from agent": "Recebido do agente",
"Number That Received the Service": "Número que recebeu o serviço",
"The phone number that received the float, credit or service.": "O número que recebeu o float, o saldo ou o serviço.",
"Agent WhatsApp / Phone": "WhatsApp / telefone do agente",
"Agent Type": "Tipo de agente",
"Regular Agent": "Agente normal",
"Master Agent": "Agente principal",
"Type the amount you paid to the agent, or received from the agent.": "Escreva o valor pago ao agente ou recebido do agente.",
"This Entry": "Esta operação",
"This Sale": "Esta venda",
"Fully paid": "Pago na totalidade",
"Referring Agent": "Agente angariador",
"Service": "Serviço",
"Data Sending": "Envio de internet",
"Deposit": "Depósito",
"EVC": "EVC",
"Amount (or the Day's Total)": "Valor (ou total do dia)",
"Commission Rate (%)": "Taxa de comissão (%)",
"Agent's Share (%)": "Parte do agente (%)",
"Client Name": "Nome do cliente",
"Client Phone": "Telefone do cliente",
"Agent's Cut": "Parte do agente",
"You Keep": "Fica consigo",
"New Referral Sale": "Nova venda de angariador",
"Edit Referral Sale": "Editar venda de angariador",
"New Wallet Commission": "Nova comissão de carteira",
"Edit Wallet Commission": "Editar comissão de carteira",
"Month": "Mês",
"Wallet": "Carteira",
"Commission on Statement": "Comissão no extrato",
"Commission Paid to You": "Comissão paga a si",
"Shared with an Agent or Partner": "Partilhado com um agente ou parceiro",
"Agent or Partner Name": "Nome do agente ou parceiro",
"Net Commission": "Comissão líquida",
"New EVC Entry": "Nova entrada EVC",
"Edit EVC Entry": "Editar entrada EVC",
"EVC Operator": "Operador EVC",
"Purchase Amount": "Valor da compra",
"Part Sold to Other Dealers": "Parte vendida a outros revendedores",
"Wholesale. Leave empty if you sold it all to customers.": "Por grosso. Deixe vazio se vendeu tudo a clientes.",
"Dealer Name": "Nome do revendedor",
"Operator Commission Rate (%)": "Taxa de comissão do operador (%)",
"The percentage the operator gives you on what you buy.": "A percentagem que o operador lhe dá sobre o que compra.",
"Share Paid to Partner on Retail Sales (%)": "Parte paga ao parceiro nas vendas a retalho (%)",
"Share Paid to Partner on Wholesale (%)": "Parte paga ao parceiro na venda por grosso (%)",
"Only if you share part of your commission with a partner or line owner. Otherwise leave it at 0.": "Só se partilhar parte da comissão com um parceiro ou dono da linha. Caso contrário, deixe 0.",
"Retail Part": "Parte a retalho",
"Total Commission": "Comissão total",
"Shared with Partner": "Partilhado com o parceiro",
"Passed to Dealer": "Passado ao revendedor",
"What Was It For?": "Para que foi?",
"Paid From": "Pago de",
"Type an amount greater than 0.": "Escreva um valor maior que 0.",
"Log an Error": "Registar um erro",
"Edit Error": "Editar erro",
"Date Found": "Data em que foi encontrado",
"Type of Error": "Tipo de erro",
"What Happened": "O que aconteceu",
"Did It Cost Money?": "Custou dinheiro?",
"Amount Lost": "Valor perdido",
"Caused By": "Causado por",
"Found By": "Encontrado por",
"How It Was Fixed": "Como foi corrigido",
"Date Fixed": "Data da correção",
"Open": "Aberto",
"In Progress": "Em curso",
"Fixed": "Corrigido",
"Yes": "Sim",
"No": "Não",
"Record a Payment on This Sale": "Registar um pagamento nesta venda",
"Payment recorded": "Pagamento registado",
"Delete this entry? This cannot be undone.": "Eliminar esta operação? Não pode ser desfeito.",
"Total You Counted": "Total que contou",
"You Should Have": "Deveria ter",
"Difference": "Diferença",
"None, it balances": "Nenhuma, bate certo",
"This is your first record. The next one will be checked against it.": "É o seu primeiro registo. O seguinte será comparado com este.",
"Add Another Account or Wallet": "Adicionar outra conta ou carteira",
"Name of the new account or wallet. For example: a bank, a new wallet, or money kept at home.": "Nome da nova conta ou carteira. Por exemplo: um banco, uma carteira nova ou dinheiro guardado em casa.",
"That account is already in the list.": "Essa conta já está na lista.",
"Saved. Your money balances.": "Guardado. O seu dinheiro bate certo.",
"Saved. This is your starting point for the next check.": "Guardado. É o seu ponto de partida para a próxima verificação.",
"Cash": "Dinheiro",
"Cash in Hand": "Dinheiro em mão",
"Bank": "Banco",
"Bank Transfer": "Transferência bancária",
"EVC Stock": "Stock EVC",
"Bank-to-Wallet": "Banco para carteira",
"Wallet-to-Bank": "Carteira para banco",
"Wallet-to-Wallet": "Carteira para carteira",
"Bank to Wallet Exchange": "Câmbio banco para carteira",
"Wallet to Bank Exchange": "Câmbio carteira para banco",
"Bank to Bank Exchange": "Câmbio banco para banco",
"Float Transfer/Rebalancing (between wallets)": "Transferência/reequilíbrio de float (entre carteiras)",
"EVC/Voucher Transaction": "Operação EVC/voucher",
"Data / Airtime Purchase": "Compra de internet / saldo",
"Rent": "Renda",
"Transport": "Transporte",
"Staff": "Pessoal",
"Bank Charges": "Taxas bancárias",
"Owner Withdrawal": "Levantamento do dono",
"Other": "Outro",
"Business decision (waived)": "Decisão comercial (perdoado)",
"Customer unreachable/disappeared": "Cliente incontactável ou desaparecido",
"Fraud/Scam": "Fraude/burla",
"Error-caused loss": "Perda causada por erro",
"Wrong amount charged": "Valor errado cobrado",
"Wrong customer/agent billed": "Cliente ou agente errado faturado",
"Duplicate entry": "Operação duplicada",
"Wrong exchange rate": "Taxa de câmbio errada",
"Wrong data bundle": "Pacote de internet errado",
"Reconciliation mismatch": "Diferença na reconciliação",
"Owner/Staff": "Dono/pessoal",
"System/Technical": "Sistema/técnico",
"Unclear": "Não está claro",
"Gambia": "Gâmbia",
"Senegal": "Senegal",
"Guinea": "Guiné",
"Mali": "Mali",
"Guinea-Bissau": "Guiné-Bissau",
"Sierra Leone": "Serra Leoa",
"Liberia": "Libéria",
"Ghana": "Gana",
"Nigeria": "Nigéria",
"Côte d'Ivoire": "Costa do Marfim",
"Burkina Faso": "Burkina Faso",
"Togo": "Togo",
"Benin": "Benim",
"Niger": "Níger",
"Mauritania": "Mauritânia",
"Cabo Verde": "Cabo Verde",
"Morocco": "Marrocos",
"Algeria": "Argélia",
"Tunisia": "Tunísia",
"Egypt": "Egito",
"Cameroon": "Camarões",
"DR Congo": "RD Congo",
"Congo": "Congo",
"Gabon": "Gabão",
"Kenya": "Quénia",
"Uganda": "Uganda",
"Tanzania": "Tanzânia",
"Rwanda": "Ruanda",
"Ethiopia": "Etiópia",
"South Africa": "África do Sul",
"United States": "Estados Unidos",
"Canada": "Canadá",
"United Kingdom": "Reino Unido",
"France": "França",
"Germany": "Alemanha",
"Spain": "Espanha",
"Italy": "Itália",
"Netherlands": "Países Baixos",
"Belgium": "Bélgica",
"Portugal": "Portugal",
"Türkiye": "Turquia",
"Saudi Arabia": "Arábia Saudita",
"United Arab Emirates": "Emirados Árabes Unidos",
"India": "Índia",
"Pakistan": "Paquistão",
"China": "China",
"Brazil": "Brasil",
"Australia": "Austrália",
"Classic": "Clássico",
"Create account": "Criar conta",
"Sign in": "Entrar",
"This phone only": "Só este telemóvel",
"Your name or business name": "O seu nome ou da sua empresa",
"Your Name or Business Name": "O seu nome ou da sua empresa",
"Password, at least 6 characters": "Palavra-passe, pelo menos 6 caracteres",
"Create my account": "Criar a minha conta",
"By continuing you accept the": "Ao continuar, aceita a",
"privacy policy": "política de privacidade",
"Forgot password?": "Esqueceu a palavra-passe?",
"Your records stay only on this phone. You can create an account later to keep them online.": "Os seus registos ficam só neste telemóvel. Pode criar uma conta mais tarde para os guardar online.",
"Start using the app": "Começar a usar",
"Record data sales, wallet transfers and agent deals. Track every debt. Works without internet.": "Registe vendas de internet, transferências de carteira e operações com agentes. Acompanhe cada dívida. Funciona sem internet.",
"Record data sales, deposits and wallet transfers": "Registe vendas de internet, depósitos e transferências",
"Track agent deals and float, both ways": "Acompanhe operações e float com agentes, nos dois sentidos",
"See who owes you and who might not pay": "Veja quem lhe deve e quem pode não pagar",
"Check that your money balances every day": "Verifique todos os dias se o seu dinheiro bate certo",
"You are offline. You can use the app on this phone now and create an account later.": "Está sem internet. Pode usar a aplicação neste telemóvel e criar uma conta mais tarde.",
"Connecting…": "A ligar…",
"Tell us who this account belongs to. Your name appears on your home screen.": "Diga-nos a quem pertence esta conta. O seu nome aparece no ecrã inicial.",
"Sets your currency and how phone numbers are checked. You can change them later.": "Define a sua moeda e como os números são verificados. Pode mudar mais tarde.",
"Skip for now": "Agora não",
"I have a backup file to restore": "Tenho uma cópia de segurança para restaurar",
"Type your name or business name.": "Escreva o seu nome ou da sua empresa.",
"Type your name or business name, or tap Skip for now.": "Escreva o seu nome ou da sua empresa, ou toque em Agora não.",
"Type your email and a password.": "Escreva o seu e-mail e uma palavra-passe.",
"Type your email and password.": "Escreva o seu e-mail e palavra-passe.",
"Type your email address.": "Escreva o seu endereço de e-mail.",
"Type your email first.": "Escreva primeiro o seu e-mail.",
"Type a password.": "Escreva uma palavra-passe.",
"Creating your account…": "A criar a sua conta…",
"Choose a PIN": "Escolha um PIN",
"Protect your records. Choose 4 to 6 digits that only you know.": "Proteja os seus registos. Escolha 4 a 6 algarismos que só você conhece.",
"Type the PIN again": "Escreva o PIN outra vez",
"Type the same PIN once more.": "Escreva o mesmo PIN mais uma vez.",
"The two PINs did not match. Start again.": "Os dois PINs não coincidem. Comece de novo.",
"Next": "Seguinte",
"Not now": "Agora não",
"The PIN is required while you are signed in to an account.": "O PIN é obrigatório quando tem sessão iniciada numa conta.",
"Use your fingerprint too?": "Usar também a impressão digital?",
"Open the app with your fingerprint or face. Your PIN always works as a back-up.": "Abra a aplicação com a impressão digital ou o rosto. O PIN funciona sempre como alternativa.",
"Use Fingerprint": "Usar impressão digital",
"Your PIN is on": "O seu PIN está ativo",
"Enter your PIN to open your records": "Escreva o PIN para abrir os seus registos",
"Wrong PIN. Try again.": "PIN errado. Tente outra vez.",
"Forgot PIN?": "Esqueceu o PIN?",
"Forgot your PIN?": "Esqueceu o PIN?",
"Use Fingerprint or Face": "Usar impressão digital ou rosto",
"Fingerprint did not work. Type your PIN.": "A impressão digital não funcionou. Escreva o PIN.",
"Type your account password. Then you can choose a new PIN.": "Escreva a palavra-passe da conta. Depois pode escolher um PIN novo.",
"Reset My PIN": "Repor o meu PIN",
"Your password is right. Choose a new PIN.": "A palavra-passe está certa. Escolha um PIN novo.",
"You do not have an account, so there is no way to prove who you are. Your records are only on this phone.": "Não tem conta, por isso não há forma de provar quem é. Os seus registos estão só neste telemóvel.",
"If you saved a backup, you can erase this phone, start over and restore the backup. Anything not in a backup will be lost.": "Se guardou uma cópia, pode apagar este telemóvel, recomeçar e restaurar a cópia. O que não estiver na cópia perde-se.",
"Erase This Phone and Start Over": "Apagar este telemóvel e recomeçar",
"Erase everything on this phone and start over? Records that are only on this phone, and not in a backup, will be lost for good.": "Apagar tudo neste telemóvel e recomeçar? Os registos que estão só neste telemóvel, e não numa cópia, perdem-se para sempre.",
"Last check: erase all records on this phone?": "Última confirmação: apagar todos os registos deste telemóvel?",
"Please sign in again": "Por favor, entre outra vez",
"Type your password.": "Escreva a palavra-passe.",
"Checking…": "A verificar…",
"Sign out": "Terminar sessão",
"Too many tries. Wait a few minutes, then try again.": "Demasiadas tentativas. Espere alguns minutos e tente outra vez.",
"Wrong email or password.": "E-mail ou palavra-passe errados.",
"An account with this email already exists. Tap Sign in instead.": "Já existe uma conta com este e-mail. Toque em Entrar.",
"No account with this email. Tap Create account first.": "Não há conta com este e-mail. Toque primeiro em Criar conta.",
"That email address does not look right.": "Esse endereço de e-mail não parece correto.",
"Use a password of at least 6 characters.": "Use uma palavra-passe com pelo menos 6 caracteres.",
"No internet connection. Try again when you are online.": "Sem ligação à internet. Tente outra vez quando estiver online.",
"That password belongs to a different account.": "Essa palavra-passe pertence a outra conta.",
"For your safety, type your password again, then try once more.": "Por segurança, escreva a palavra-passe outra vez e tente de novo.",
"Something went wrong.": "Algo correu mal.",
"Sign in first.": "Entre primeiro.",
"Cannot reach Firebase right now. Your changes are kept and will sync later.": "Não é possível ligar ao servidor agora. As alterações ficam guardadas e serão enviadas depois.",
"Still connecting to Firebase. Check your internet, then try again.": "Ainda a ligar ao servidor. Verifique a internet e tente outra vez.",
"Account created. Uploading your records.": "Conta criada. A enviar os seus registos.",
"Signed in. Bringing in your records.": "Sessão iniciada. A trazer os seus registos.",
"This phone was removed from the account.": "Este telemóvel foi removido da conta.",
"Synced": "Sincronizado",
"Syncing": "A sincronizar",
"Offline": "Sem internet",
"Sign in to sync": "Entrar para sincronizar",
"Connecting": "A ligar",
"Sync not reachable": "Sincronização indisponível",
"Sync problem": "Problema de sincronização",
"Android phone": "Telemóvel Android",
"Windows computer": "Computador Windows",
"Linux computer": "Computador Linux",
"Phone": "Telefone",
"Account and Security": "Conta e segurança",
"Your Account": "A sua conta",
"Security": "Segurança",
"Look and Money": "Aspeto e dinheiro",
"Country, Currency and Theme": "País, moeda e cores",
"Money Rules": "Regras de dinheiro",
"Tips and how you record payments": "Gorjetas e como regista pagamentos",
"Your Choices": "As suas listas",
"Payment channels, wallets, EVC operators and other lists": "Meios de pagamento, carteiras, operadores EVC e outras listas",
"Your Data": "Os seus dados",
"Your data": "Os seus dados",
"Backup and Restore": "Cópia de segurança e restauro",
"Save a copy of your records": "Guarde uma cópia dos seus registos",
"Privacy Policy": "Política de privacidade",
"Privacy policy": "Política de privacidade",
"How your records are protected": "Como os seus registos são protegidos",
"How It Works": "Como funciona",
"Balances, credit, tips, statuses": "Saldos, crédito, gorjetas, estados",
"Lock the App Now": "Bloquear agora",
"Your Details": "Os seus dados",
"Sign in to keep records online": "Entre para guardar os registos online",
"Protect your records with a PIN": "Proteja os seus registos com um PIN",
"PIN and fingerprint on": "PIN e impressão digital ativos",
"PIN on": "PIN ativo",
"Add your name": "Adicione o seu nome",
"App Lock": "Bloqueio da aplicação",
"On": "Ativo",
"Off": "Desativado",
"The app asks for your PIN every time it opens or comes back from another app.": "A aplicação pede o PIN sempre que abre ou volta de outra aplicação.",
"Without a lock, anyone who picks up your phone can open your records.": "Sem bloqueio, qualquer pessoa que pegue no telemóvel pode abrir os seus registos.",
"Set a PIN": "Definir um PIN",
"Change PIN": "Mudar o PIN",
"Turn Off": "Desativar",
"Turn off the PIN? Anyone who picks up your phone will be able to open your records.": "Desativar o PIN? Qualquer pessoa que pegue no telemóvel poderá abrir os seus registos.",
"PIN turned off": "PIN desativado",
"Type your current PIN": "Escreva o PIN atual",
"Fingerprint or Face": "Impressão digital ou rosto",
"Turn On Fingerprint": "Ativar impressão digital",
"Turn Off Fingerprint": "Desativar impressão digital",
"Fingerprint is on": "A impressão digital está ativa",
"Fingerprint is off": "A impressão digital está desativada",
"Could not turn on fingerprint on this phone.": "Não foi possível ativar a impressão digital neste telemóvel.",
"Could not turn on fingerprint. Your PIN still works.": "Não foi possível ativar a impressão digital. O PIN continua a funcionar.",
"This phone or browser does not offer fingerprint unlock for the app.": "Este telemóvel ou navegador não oferece desbloqueio por impressão digital.",
"Lock Automatically": "Bloqueio automático",
"Right away": "Imediatamente",
"Only when I lock it": "Só quando eu bloquear",
"Never": "Nunca",
"How long the app can be out of sight before it asks for your PIN again.": "Quanto tempo a aplicação pode ficar fora de vista antes de pedir o PIN outra vez.",
"Hide Amounts": "Esconder valores",
"Hide amounts": "Esconder valores",
"Show Amounts": "Mostrar valores",
"Show amounts": "Mostrar valores",
"Blur money amounts on screen so people nearby cannot read them. You can also tap the eye at the top of any screen.": "Desfoca os valores no ecrã para que quem está perto não os consiga ler. Também pode tocar no olho no topo de qualquer ecrã.",
"Ask for Your Password Again": "Pedir a palavra-passe outra vez",
"After this many days the app asks for your email password again, even with the PIN.": "Depois destes dias, a aplicação pede outra vez a palavra-passe da conta, mesmo com o PIN.",
"Your Devices": "Os seus aparelhos",
"Every phone that signs in to your account is listed here. If you see one you do not know, remove it and change your password.": "Todos os telemóveis que entram na sua conta aparecem aqui. Se vir um que não conhece, remova-o e mude a palavra-passe.",
"This Phone": "Este telemóvel",
"No devices to show yet.": "Ainda não há aparelhos para mostrar.",
"Remove this phone from your account? It is signed out the next time it connects.": "Remover este telemóvel da conta? A sessão termina na próxima ligação.",
"Phone removed": "Telemóvel removido",
"Could not remove it.": "Não foi possível remover.",
"A new phone signed in to your account.": "Um telemóvel novo entrou na sua conta.",
"Review": "Verificar",
"It Was Me": "Fui eu",
"What Protects Your Records": "O que protege os seus registos",
"Your records are saved on this phone and, if you have an account, in your private online account that only you can open. The PIN and fingerprint stop other people from opening the app on your phone.": "Os seus registos ficam neste telemóvel e, se tiver conta, na sua conta privada online que só você pode abrir. O PIN e a impressão digital impedem outras pessoas de abrir a aplicação no seu telemóvel.",
"Note: a text-message code for every new phone needs Firebase's paid plan. Until then, new phones are protected by your password, and you see every device here.": "Nota: um código por SMS para cada telemóvel novo exige o plano pago do Firebase. Até lá, os telemóveis novos são protegidos pela palavra-passe, e vê aqui todos os aparelhos.",
"Colour Theme": "Cores",
"Classic suits everyone. The country themes use that country's flag colours. Red always means money to collect, and green always means money received.": "Clássico serve para todos. Os temas dos países usam as cores da bandeira. Vermelho é sempre dinheiro a receber, e verde dinheiro recebido.",
"Your country decides how phone numbers are checked. Contacts in other countries can still be recorded: choose their country next to the phone box.": "O seu país decide como os números são verificados. Pode registar contactos de outros países: escolha o país ao lado do número.",
"Use This Country's Currency and Colours": "Usar a moeda e as cores deste país",
"Country, currency and colours updated": "País, moeda e cores atualizados",
"Save Currency": "Guardar moeda",
"Currency saved": "Moeda guardada",
"Type a currency symbol of up to 8 characters.": "Escreva um símbolo de moeda com até 8 caracteres.",
"Also use this country's currency and colours": "Usar também a moeda e as cores deste país",
"How Do You Handle Tips?": "Como trata as gorjetas?",
"Extra money on top": "Dinheiro extra",
"Included in the amount received": "Incluída no valor recebido",
"Not mine, I hand it over": "Não é minha, eu entrego",
"Tips belong to staff or someone else. They count as money received, but show as Tips to Hand Over and not as your income.": "As gorjetas pertencem ao pessoal ou a outra pessoa. Contam como dinheiro recebido, mas aparecem como Gorjetas a entregar e não como rendimento seu.",
"Tips always show on your home screen and are never lost, whichever way you choose.": "As gorjetas aparecem sempre no ecrã inicial e nunca se perdem, seja qual for a escolha.",
"Tip rule saved": "Regra das gorjetas guardada",
"How Do You Record Sales?": "Como regista as vendas?",
"Ask me every time": "Perguntar sempre",
"Recommended. You choose Paid in Full, Part Paid or On Credit for each sale, so it is never recorded by mistake.": "Recomendado. Escolhe Pago na totalidade, Pago em parte ou A crédito em cada venda, para nada ser registado por engano.",
"Mostly paid on the spot": "Quase sempre pago na hora",
"Paid in Full is pre-selected on new sales. You still see it clearly and can change it.": "Pago na totalidade fica pré-escolhido nas vendas novas. Continua a vê-lo e pode mudar.",
"Mostly on credit (debt recording)": "Quase sempre a crédito (registo de dívidas)",
"On Credit is pre-selected on new sales. Use this if you mainly record who owes you.": "A crédito fica pré-escolhido nas vendas novas. Use se regista sobretudo quem lhe deve.",
"Change the choices that appear in your forms. Put one item on each line. You can add your own, for example another wallet or EVC operator.": "Mude as escolhas que aparecem nos formulários. Um item por linha. Pode adicionar os seus, por exemplo outra carteira ou operador EVC.",
"Payment Channels": "Meios de pagamento",
"Commission Wallets": "Carteiras com comissão",
"EVC Operators": "Operadores EVC",
"Capital and Cash Accounts": "Contas de capital e caixa",
"Money Out Categories": "Tipos de saídas de dinheiro",
"Wallet Exchange Types": "Tipos de câmbio de carteira",
"Agent Transaction Types": "Tipos de operações de agentes",
"Write-Off Reasons": "Motivos das perdas",
"Error Types": "Tipos de erros",
"Who Caused an Error": "Quem causou um erro",
"Save My Choices": "Guardar as minhas listas",
"Your choices are saved": "As suas listas foram guardadas",
"Keep your records online": "Guarde os registos online",
"Create an account or sign in to keep your records online and on any phone. Records already on this phone are added to your account.": "Crie uma conta ou entre para guardar os registos online e em qualquer telemóvel. Os registos que já estão neste telemóvel são adicionados à conta.",
"Create Account": "Criar conta",
"Sign In": "Entrar",
"Signed in as": "Sessão iniciada como",
"Changes waiting to go online": "Alterações à espera de envio",
"Last synced": "Última sincronização",
"Sync now": "Sincronizar agora",
"Changes are saved on this phone first, then sent to your account in the background. Signing out removes your records from this phone; they come back when you sign in again.": "As alterações ficam primeiro neste telemóvel e depois são enviadas para a conta. Ao terminar a sessão, os registos saem deste telemóvel; voltam quando entrar outra vez.",
"Sign out? Your records are removed from this phone and come back when you sign in again.": "Terminar sessão? Os registos saem deste telemóvel e voltam quando entrar outra vez.",
"Sign out? Your records stay on this phone, but stop syncing until you sign in again.": "Terminar sessão? Os registos ficam neste telemóvel, mas deixam de sincronizar até entrar outra vez.",
"Delete account": "Eliminar conta",
"Delete my account and records": "Eliminar a minha conta e registos",
"This permanently deletes your account and all your records, online and on this phone. It cannot be undone.": "Isto elimina para sempre a conta e todos os registos, online e neste telemóvel. Não pode ser desfeito.",
"This permanently deletes your account and every record in it, online and on this phone.": "Isto elimina para sempre a conta e todos os registos, online e neste telemóvel.",
"Type your password to confirm": "Escreva a palavra-passe para confirmar",
"Delete everything": "Eliminar tudo",
"Last check: delete your account and every record for good?": "Última confirmação: eliminar para sempre a conta e todos os registos?",
"Your account and records were deleted": "A conta e os registos foram eliminados",
"Send Me a Password Reset Email": "Enviar-me um e-mail para repor a palavra-passe",
"This app already has its online account built in.": "Esta aplicação já tem a conta online incluída.",
"Back up": "Fazer cópia",
"You have not saved a backup yet. Your records only live on this phone.": "Ainda não fez uma cópia de segurança. Os registos estão só neste telemóvel.",
"You have not saved a backup yet.": "Ainda não fez uma cópia de segurança.",
"Your records live only on this phone.": "Os seus registos estão só neste telemóvel.",
"If the phone is lost, or the app's data is cleared, they are gone unless you have a backup. Save one at least once a week and keep a copy off the phone, for example on Google Drive or sent to yourself on WhatsApp. Or create an account in Settings, then Your Account.": "Se perder o telemóvel, ou se os dados da aplicação forem apagados, perdem-se sem cópia. Faça uma pelo menos uma vez por semana e guarde-a fora do telemóvel, por exemplo no Google Drive ou enviada para si no WhatsApp. Ou crie uma conta em Definições, depois A sua conta.",
"Last backup": "Última cópia",
"Save backup to phone": "Guardar cópia no telemóvel",
"Send backup to Drive or WhatsApp": "Enviar cópia para o Drive ou WhatsApp",
"Backup saved": "Cópia guardada",
"Restore from a backup file": "Restaurar a partir de uma cópia",
"Use this to bring back a backup, or to move your records to a new phone. It replaces everything currently in the app.": "Use para recuperar uma cópia, ou passar os registos para um telemóvel novo. Substitui tudo o que está na aplicação.",
"Records restored": "Registos restaurados",
"That file is not a backup from this app.": "Esse ficheiro não é uma cópia desta aplicação.",
"Spreadsheet": "Folha de cálculo",
"Download all sales as a spreadsheet file that opens in Excel.": "Descarregue todas as vendas num ficheiro que abre no Excel.",
"Download sales for Excel": "Descarregar vendas para Excel",
"Not saved: your phone storage may be full.": "Não guardado: a memória do telemóvel pode estar cheia.",
"Everything stays on this phone and works without internet. Back it up every week from Settings, then Backup and Restore.": "Tudo fica neste telemóvel e funciona sem internet. Faça uma cópia todas as semanas em Definições, depois Cópia de segurança e restauro.",
"If you want to keep a copy, save a backup first in Settings, then Backup and Restore.": "Se quiser guardar uma cópia, faça primeiro uma cópia em Definições, depois Cópia de segurança e restauro.",
"Agent & Client Tracker · Your records are private to you.": "Agent & Client Tracker · Os seus registos são só seus.",
"To collect and to pay": "A receber e a pagar",
"\"To collect\" is money someone must still pay you. \"To pay\" is money you must still pay someone. \"Credit\" means a customer paid you in advance.": "«A receber» é dinheiro que alguém ainda lhe tem de pagar. «A pagar» é dinheiro que ainda tem de pagar a alguém. «Crédito» quer dizer que um cliente pagou adiantado.",
"Choosing the date": "Escolher a data",
"New entries have no date until you tap Today, Yesterday or Other date, so a past sale is never saved with today's date by mistake. The Save button shows the date you chose.": "As operações novas não têm data até tocar em Hoje, Ontem ou Outra data, para uma venda antiga nunca ficar com a data de hoje por engano. O botão Guardar mostra a data escolhida.",
"Phone numbers": "Números de telefone",
"Each customer gets a risk score from what they owe, how long it has been unpaid, late payments and write-offs. Low risk can get credit up to their limit; High risk should pay on the spot. You can change any customer's credit limit.": "Cada cliente recebe uma nota de risco conforme o que deve, há quanto tempo, atrasos e perdas. Risco baixo: pode ter crédito até ao limite; risco elevado: deve pagar na hora. Pode mudar o limite de crédito de qualquer cliente.",
"\"Paid to Agent\" is money or float you sent to the agent. \"Received from Agent\" is what they sent you. If you paid more than you received, it shows as To Collect. If you received more, it shows as To Pay.": "«Pago ao agente» é dinheiro ou float que enviou ao agente. «Recebido do agente» é o que ele lhe enviou. Se pagou mais do que recebeu, aparece em A receber. Se recebeu mais, aparece em A pagar.",
"\"Paid to Agent\" is money or float you sent to them. \"Received from Agent\" is money they sent to you. \"To Collect\" means they must pay you; \"To Pay\" means you must pay them.": "«Pago ao agente» é dinheiro ou float que lhe enviou. «Recebido do agente» é dinheiro que ele lhe enviou. «A receber»: ele tem de lhe pagar; «A pagar»: tem de lhe pagar a ele.",
"Recording quickly": "Registar depressa",
"For every sale you choose Paid in Full, Part Paid or On Credit, so nothing is recorded as paid by mistake. \"Save, Add Another\" keeps the form open with the same date. Use \"Customer Paid\" when someone pays off what they owe without buying anything, and \"Several Sales at Once\" to type many sales together.": "Em cada venda escolhe Pago na totalidade, Pago em parte ou A crédito, para nada ficar pago por engano. «Guardar e adicionar outro» mantém o formulário aberto com a mesma data. Use «Pagamento de cliente» quando alguém paga o que deve sem comprar nada, e «Várias vendas de uma vez» para escrever muitas vendas juntas.",
"Paying an old debt late": "Pagar uma dívida antiga com atraso",
"Open the old sale and tap \"Record a payment\", or put the full amount on the new sale. A payment covers its own sale first, and anything extra pays off the oldest unpaid sales. Either way the old sale turns Paid and the app records how many days late it was paid.": "Abra a venda antiga e toque em «Registar um pagamento», ou ponha o valor todo na venda nova. Um pagamento cobre primeiro a sua venda, e o resto paga as vendas por pagar mais antigas. De qualquer forma, a venda antiga fica Paga e a aplicação regista os dias de atraso.",
"Paying in advance": "Pagar adiantado",
"Nothing extra to do. If a customer overpaid before, their next sale is covered automatically, even if they pay nothing that day. If the credit only covers part of it, the account shows just what is left.": "Não precisa de fazer nada. Se um cliente pagou a mais antes, a próxima venda fica coberta automaticamente, mesmo que não pague nada nesse dia. Se o crédito só cobrir parte, a conta mostra só o que falta.",
"Statuses": "Estados",
"Customer types": "Tipos de clientes",
"Commission = purchase x operator rate. Shared with Partner = retail part x your partner's retail share, plus wholesale part x their wholesale share. On the wholesale part, the rest goes to the dealer.": "Comissão = compra x taxa do operador. Partilhado com o parceiro = parte a retalho x parte do parceiro a retalho, mais parte por grosso x a sua parte por grosso. Na parte por grosso, o resto vai para o revendedor.",
"Record what you have in every wallet, bank and your cash drawer. The app compares it with what you should have: your last balances, plus money in, minus money out. A difference of zero means no money is missing.": "Registe o que tem em cada carteira, no banco e na caixa. A aplicação compara com o que deveria ter: os últimos saldos, mais as entradas, menos as saídas. Uma diferença de zero quer dizer que não falta dinheiro.",
"Record your balances once to begin. From the second time, the app checks that your money adds up.": "Registe os saldos uma vez para começar. A partir da segunda vez, a aplicação verifica se o dinheiro bate certo.",
"Tap the green button to record your balances.": "Toque no botão verde para registar os saldos.",
"How It Adds Up": "As contas",
"Balances You Recorded": "Saldos que registou",
"+ Payments from customers": "+ Pagamentos de clientes",
"+ Tips": "+ Gorjetas",
"+ Received from agents": "+ Recebido de agentes",
"− Paid to agents": "− Pago a agentes",
"− Expenses and money out": "− Despesas e saídas de dinheiro",
"You should have": "Deveria ter",
"You counted": "Contou",
"Change These Balances": "Alterar estes saldos",
"This record may have been removed.": "Este registo pode ter sido removido.",
"For each month: your balances at the start, plus money in, minus money out, is what you should have at the end. This is compared with the balances you recorded. It does not need a bank statement.": "Para cada mês: os saldos no início, mais as entradas, menos as saídas, dão o que deveria ter no fim. Compara-se com os saldos que registou. Não precisa de extrato bancário.",
"Months appear here as you record sales and balances.": "Os meses aparecem aqui quando regista vendas e saldos.",
"Record your balances at the end of this month to check it.": "Registe os saldos no fim deste mês para o verificar.",
"Record your balances at the start of the month too, so the app can check this month.": "Registe também os saldos no início do mês, para a aplicação poder verificar este mês.",
"Record your balances": "Registe os seus saldos",
"Record money that left your business: data or airtime you bought, rent, transport, withdrawals. These make your Daily Cash Check and Monthly Balance Check accurate.": "Registe o dinheiro que saiu do negócio: internet ou saldo que comprou, renda, transporte, levantamentos. Isto torna certas as verificações diária e mensal.",
"Tap the red button to record money out.": "Toque no botão vermelho para registar uma saída de dinheiro.",
"Record your balances whenever you like. Money to collect and money to pay always use today's live totals. The same balances are used for your Daily Cash Check.": "Registe os saldos quando quiser. O dinheiro a receber e a pagar usa sempre os totais de hoje. Os mesmos saldos servem para a verificação diária de caixa.",
"Available Capital": "Capital disponível",
"Available capital": "Capital disponível",
"Available capital, plus money to collect, minus money to pay": "Capital disponível, mais o dinheiro a receber, menos o dinheiro a pagar",
"From customers and agents": "De clientes e agentes",
"To agents, plus what customers paid in advance": "A agentes, mais o que os clientes pagaram adiantado",
"Your Recorded Balances": "Os seus saldos registados",
"High risk customers": "Clientes de risco elevado",
"Medium risk customers": "Clientes de risco médio",
"Money at risk": "Dinheiro em risco",
"To collect from medium and high risk customers": "A receber de clientes de risco médio e elevado",
"Warnings": "Alertas",
"No warnings right now.": "Sem alertas de momento.",
"No customer has money to pay. Well done.": "Nenhum cliente tem dinheiro a pagar. Muito bem.",
"Agents with money to pay you": "Agentes com dinheiro a pagar-lhe",
"How the risk score works": "Como funciona a nota de risco",
"Suggested credit: Low risk regular customers up to two of their usual purchases; other Low risk customers one; Medium risk one; High risk none. Tap \"Set credit limit\" to choose your own.": "Crédito sugerido: clientes regulares de risco baixo, até duas compras habituais; outros de risco baixo, uma; risco médio, uma; risco elevado, nenhuma. Toque em «Definir limite de crédito» para escolher.",
"Set credit limit": "Definir limite de crédito",
"Set Credit Limit": "Definir limite de crédito",
"Credit limit saved": "Limite de crédito guardado",
"Type a number, for example 500.": "Escreva um número, por exemplo 500.",
"No credit: pay on the spot": "Sem crédito: pagar na hora",
"No warning signs.": "Sem sinais de alerta.",
"Low risk": "Risco baixo",
"Medium risk": "Risco médio",
"High risk": "Risco elevado",
"Low": "Baixo",
"Medium": "Médio",
"High": "Elevado",
"Bad or No Credit": "Mau ou sem crédito",
"Credit": "Crédito",
"Days Overdue": "Dias de atraso",
"Oldest Unpaid": "Mais antigo por pagar",
"Total Billed": "Total faturado",
"Total Paid": "Total pago",
"Written Off": "Perdido",
"First Sale": "Primeira venda",
"Last Sale": "Última venda",
"Sales per Month": "Vendas por mês",
"Their Sales, Newest First": "As suas vendas, mais recentes primeiro",
"Customers appear here automatically when you add sales.": "Os clientes aparecem aqui automaticamente quando adiciona vendas.",
"They may have been removed.": "Podem ter sido removidos.",
"Last Entry": "Última operação",
"Entries": "Operações",
"No agent entries yet": "Ainda sem operações de agentes",
"Tap the green button to record a float transfer, EVC, bank exchange or other agent entry.": "Toque no botão verde para registar uma transferência de float, EVC, câmbio bancário ou outra operação.",
"Tap the green button to record your first sale.": "Toque no botão verde para registar a primeira venda.",
"Tap the green button to add one.": "Toque no botão verde para adicionar.",
"Message: Change Any Word Before Sending": "Mensagem: mude o que quiser antes de enviar",
"Send on WhatsApp": "Enviar no WhatsApp",
"Start Over": "Recomeçar",
"No phone number saved for them, so use Share or Copy.": "Sem número guardado, use Partilhar ou Copiar.",
"No one yet": "Ninguém ainda",
"Press and hold the message to copy it.": "Prima e mantenha a mensagem para a copiar.",
"Press and hold the text to copy it.": "Prima e mantenha o texto para o copiar.",
"Purchase": "Compra",
"Mobile Wallets": "Carteiras móveis",
"By Month": "Por mês",
"Mobile Wallets, Net": "Carteiras móveis, líquido",
"EVC, Net": "EVC, líquido",
"Total You Earned": "Total ganho",
"This Month": "Este mês",
"New Commission": "Nova comissão",
"Commission entries": "Comissões registadas",
"One entry per wallet per month. Net is what you received, minus anything you shared with an Agent or Partner.": "Uma linha por carteira por mês. O líquido é o que recebeu, menos o que partilhou com um agente ou parceiro.",
"One row per purchase. You earn commission on the part you sell to customers (Retail). The part you sell on to other dealers (Wholesale) is passed on to them. If you share part of your commission with a partner or line owner, enter it in the form and it is taken off for you.": "Uma linha por compra. Ganha comissão na parte que vende a clientes (retalho). A parte vendida a outros revendedores (grosso) passa para eles. Se partilhar parte da comissão com um parceiro ou dono da linha, indique no formulário e é descontada.",
"Net, after partner and agent shares.": "Líquido, depois das partes de parceiros e agentes.",
"Nothing yet. Add commission entries from the home screen, under Commissions.": "Nada ainda. Adicione comissões no ecrã inicial, em Comissões.",
"Monthly totals appear here once you add wallet or EVC commissions.": "Os totais mensais aparecem aqui quando adicionar comissões de carteira ou EVC.",
"Deposit Rates": "Taxas de depósito",
"Flat deposit commission by amount. A deposit gets the commission of the highest \"From\" amount it reaches.": "Comissão fixa de depósito por valor. Um depósito recebe a comissão do maior valor «De» que atinge.",
"Save rates": "Guardar taxas",
"Rates saved": "Taxas guardadas",
"For Data Sending and EVC, log one row per agent per day with that day's total. Log each Deposit on its own, because its commission depends on the amount.": "Para envio de internet e EVC, registe uma linha por agente por dia com o total do dia. Registe cada depósito à parte, porque a comissão depende do valor.",
"No referral sales yet": "Ainda sem vendas de angariadores",
"Payouts appear once you add referral sales.": "Os pagamentos aparecem quando adicionar vendas de angariadores.",
"Worked out automatically from the sales, per agent per month.": "Calculado automaticamente a partir das vendas, por agente por mês.",
"What to Pay": "O que pagar",
"Losses per month": "Perdas por mês",
"Total losses, all time": "Total de perdas, desde sempre",
"Write-offs on sales and agents, plus losses logged as errors": "Perdas em vendas e agentes, mais perdas registadas como erros",
"No losses recorded.": "Sem perdas registadas.",
"Error log": "Registo de erros",
"No errors logged.": "Sem erros registados.",
"To count an error as a loss, set \"Did it cost money?\" to Yes and fill in the amount.": "Para contar um erro como perda, ponha «Custou dinheiro?» em Sim e indique o valor.",
"Losses": "Perdas",
"Errors": "Erros",
"Main": "Principal",
"Changed to the new 9-digit number": "Mudado para o novo número de 9 algarismos",
"A 9-digit Gambian number starts with 83 (QCell), 86 (Comium) or 87 (Africell).": "Um número gambiano de 9 algarismos começa por 83 (QCell), 86 (Comium) ou 87 (Africell).",
"Gambian numbers have 9 digits (starting 83, 86 or 87), or 7 digits for Gamcel (starting 9).": "Os números gambianos têm 9 algarismos (começam por 83, 86 ou 87), ou 7 algarismos na Gamcel (começam por 9).",
"Check the number: it should have 6 to 13 digits without the country code.": "Verifique o número: deve ter 6 a 13 algarismos sem o indicativo do país.",
"Country code not recognised. Choose the country from the list instead.": "Indicativo de país desconhecido. Escolha antes o país na lista.",
"For Part Paid, the amount received must be more than 0 and less than the amount. If they paid it all, choose Paid in Full.": "Para Pago em parte, o valor recebido tem de ser mais que 0 e menos que o valor. Se pagou tudo, escolha Pago na totalidade.",
"Has more than 5 times their usual purchase to pay": "Deve mais de 5 vezes a compra habitual",
"Has more than 3 times their usual purchase to pay": "Deve mais de 3 vezes a compra habitual",
"Has more than their usual purchase to pay": "Deve mais do que a compra habitual",
"No purchase for over 60 days but still has money to pay": "Sem compras há mais de 60 dias mas ainda deve dinheiro",
"Paid: settled. Overpaid: in credit. Outstanding: unpaid for up to 3 days. Overdue: unpaid for more than 3 days. Bad debt: written off.": "Pago: liquidado. Pago a mais: com crédito. Em dívida: por pagar até 3 dias. Em atraso: por pagar há mais de 3 dias. Dívida incobrável: dada como perdida.",
"Regular means 3 or more sales and at least one a month.": "Regular quer dizer 3 ou mais vendas e pelo menos uma por mês.",
"Regular: 3 or more sales and at least one a month. Irregular: fewer. Inactive: no sale for 90 days. Bad (high risk): oldest unpaid sale is over 60 days old. Do not give credit: something was written off.": "Regular: 3 ou mais vendas e pelo menos uma por mês. Irregular: menos. Inativo: sem vendas há 90 dias. Mau (risco elevado): a venda por pagar mais antiga tem mais de 60 dias. Não dar crédito: houve uma perda.",
"Points are added for: money unpaid for a long time, owing much more than their usual purchase, paying late before, and past write-offs. 60 points or more is High risk, 30 or more is Medium.": "Somam-se pontos por: dinheiro por pagar há muito tempo, dever muito mais do que a compra habitual, atrasos anteriores e perdas anteriores. 60 pontos ou mais é risco elevado; 30 ou mais é médio.",
"Since 4 September 2026, Africell numbers start with 87, QCell with 83 and Comium with 86. Gamcel numbers stay 7 digits. Type the old 7-digit number and the app adds the right start for you when you leave the box. Old and new forms of a number count as the same person.": "Desde 4 de setembro de 2026, os números Africell começam por 87, QCell por 83 e Comium por 86. Os números Gamcel ficam com 7 algarismos. Escreva o número antigo de 7 algarismos e a aplicação acrescenta o início certo ao sair da caixa. O número antigo e o novo contam como a mesma pessoa.",
"Billed and Paid, Last 6 Months": "Faturado e pago, últimos 6 meses",
"Last 7 Days": "Últimos 7 dias",
"This Week": "Esta semana",
"settled": "liquidado",
"Nothing": "Nada",
"Billed and received by month": "Faturado e recebido por mês",
"Balances": "Saldos",
"New Entry": "Nova operação",
"New Expense": "Nova despesa",
"Nothing to pay yet": "Nada a pagar ainda",
"Paid by customers": "Pago pelos clientes",
"Paid through": "Pago por",
"Copy the rules": "Copiar as regras",
"Connect": "Ligar",
"Online sync": "Sincronização online",
"In Chrome, open console.firebase.google.com, sign in with your Google account and create a project. You can switch Google Analytics off.": "No Chrome, abra console.firebase.google.com, entre com a sua conta Google e crie um projeto. Pode desligar o Google Analytics.",
"Open Authentication, tap Get started, choose Email/Password, switch it on and save.": "Abra Authentication, toque em Get started, escolha Email/Password, ative e guarde.",
"Open Firestore Database, tap Create database, pick a location near you and start in production mode.": "Abra Firestore Database, toque em Create database, escolha um local perto de si e comece em modo de produção.",
"In Firestore, open the Rules tab, replace everything with the rules below and tap Publish. They make sure only you can see your records.": "No Firestore, abra o separador Rules, substitua tudo pelas regras abaixo e toque em Publish. Garantem que só você vê os seus registos.",
"Open Project settings (the gear), scroll to Your apps, tap the web icon </>, give it a name and register it. Copy the whole firebaseConfig block it shows and paste it below.": "Abra Project settings (a roda dentada), desça até Your apps, toque no ícone web </>, dê-lhe um nome e registe-a. Copie todo o bloco firebaseConfig que aparece e cole abaixo.",
"Once this is set up, every entry is saved to your own private online account automatically. No more backups, and you can sign in on another phone and see the same records.": "Depois de configurado, cada operação é guardada automaticamente na sua conta privada online. Sem cópias de segurança, e pode entrar noutro telemóvel e ver os mesmos registos.",
"This app needs JavaScript turned on.": "Esta aplicação precisa do JavaScript ativo.",
"Payment": "Pagamento",
"Reminder": "Lembrete",
"Reminders": "Lembretes",
"Recent": "Recentes",
"See all": "Ver tudo",
"Tools": "Ferramentas",
"Cash Check": "Caixa do dia",
"Monthly Check": "Verificação mensal",
"Capital": "Capital",
"Referrals": "Angariadores",
"Reports": "Relatórios",
"Tap New Sale to start.": "Toque em Nova venda para começar.",
"Agents and advance payments": "Agentes e pagamentos adiantados",
"Install the app": "Instalar a aplicação",
"Install": "Instalar",
"Opens like any app on your phone. Free and safe.": "Abre como qualquer aplicação do telemóvel. Grátis e seguro.",
"Tap the Share button, then Add to Home Screen.": "Toque no botão Partilhar e depois em Adicionar ao ecrã principal.",
"Install the App on This Phone": "Instalar a aplicação neste telemóvel",
"To install: tap the Share button, then Add to Home Screen.": "Para instalar: toque em Partilhar e depois em Adicionar ao ecrã principal.",
"Installing. The app will appear on your home screen.": "A instalar. A aplicação vai aparecer no ecrã principal.",
"Installed. Open it from your home screen.": "Instalada. Abra-a a partir do ecrã principal."
},
 [
  [/^(\d+) customers$/, "$1 clientes"],
  [/^(\d+) customers\. To collect: (.+)\. Paid in advance: (.+)\.$/, "$1 clientes. A receber: $2. Pago adiantado: $3."],
  [/^(\d+) entries$/, "$1 operações"],
  [/^1 entry$/, "1 operação"],
  [/^(\d+) entries, money in (.+)$/, "$1 operações, entradas $2"],
  [/^1 entry, money in (.+)$/, "1 operação, entradas $1"],
  [/^(.+), (\d+) entries$/, "$t1, $2 operações"],
  [/^(.+), 1 entry$/, "$t1, 1 operação"],
  [/^(\d+) recorded$/, "$1 registados"],
  [/^(\d+) sales, last (.+), oldest unpaid (\d+) days$/, "$1 vendas, última em $2, por pagar há $3 dias"],
  [/^(\d+) sales, last (.+)$/, "$1 vendas, última em $2"],
  [/^1 sale, last (.+)$/, "1 venda, em $1"],
  [/^(\d+) sales, paid (.+)$/, "$1 vendas, pago $2"],
  [/^(.*\d.*) to collect$/, "$1 a receber"],
  [/^(.*\d.*) out$/, "$1 de saída"],
  [/^\(was (.+)\)$/, "(antes: $1)"],
  [/^\+(\d+) (.+)$/, "+$1 $t2"],
  [/^(.+) \(\+(\d+)\)$/, "$t1 (+$2)"],
  [/^A tip is on top of the bill\. It counts as extra income and is not used to pay the bill\. Example: bill (.+), customer pays (.+) and gives a tip of (.+)\.$/, "A gorjeta é extra à conta. Conta como rendimento extra e não paga a conta. Exemplo: conta de $1, o cliente paga $2 e dá $3 de gorjeta."],
  [/^You type the total the customer paid, tip included\. The app takes the tip off before paying the bill\. Example: customer pays (.+) with a tip of (.+), so the bill gets (.+)\.$/, "Escreve o total que o cliente pagou, com a gorjeta. A aplicação tira a gorjeta antes de pagar a conta. Exemplo: o cliente paga $1 com $2 de gorjeta, por isso a conta recebe $3."],
  [/^Example: (.+)$/, "Exemplo: $1"],
  [/^After 1 minute$/, "Depois de 1 minuto"],
  [/^After (\d+) minutes$/, "Depois de $1 minutos"],
  [/^Every (\d+) days$/, "A cada $1 dias"],
  [/^Last (\d+) Days$/, "Últimos $1 dias"],
  [/^All time (.+)$/, "Desde sempre: $1"],
  [/^This month\. All time (.+)$/, "Este mês. Desde sempre: $1"],
  [/^This month: billed (.+), paid (.+), tips (.+)\.$/, "Este mês: faturado $1, pago $2, gorjetas $3."],
  [/^This month: billed (.+), paid (.+)\.$/, "Este mês: faturado $1, pago $2."],
  [/^Balances on (.+)$/, "Saldos de $1"],
  [/^Billed (.+?), paid (.+?), tip (.+?), paid (\d+) days late$/, "Faturado $1, pago $2, gorjeta $3, pago com $4 dias de atraso"],
  [/^Billed (.+?), paid (.+?), paid (\d+) days late$/, "Faturado $1, pago $2, pago com $3 dias de atraso"],
  [/^Billed (.+?), paid (.+?), tip (.+)$/, "Faturado $1, pago $2, gorjeta $3"],
  [/^Billed (.+?), paid (.+?), (\d+) days$/, "Faturado $1, pago $2, $3 dias"],
  [/^Billed (.+?), paid (.+)$/, "Faturado $1, pago $2"],
  [/^Paid to Agent (.*\d.*)$/, "Pago ao agente $1"],
  [/^Received from Agent (.*\d.*)$/, "Recebido do agente $1"],
  [/^Paid (.*\d.*)$/, "Pago $1"],
  [/^(.+) \((.+)\), to collect (.+)$/, "$1 ($2), a receber $3"],
  [/^(.+) \((.+)\), paid in advance (.+)$/, "$1 ($2), pago adiantado $3"],
  [/^(.+), to collect (.*\d.*)$/, "$1, a receber $2"],
  [/^(.+), to pay (.*\d.*)$/, "$1, a pagar $2"],
  [/^(.+), paid in advance (.*\d.*)$/, "$1, pago adiantado $2"],
  [/^(.+), settled$/, "$1, liquidado"],
  [/^Bought (.+) \(retail (.+), wholesale (.+)\)\. You keep (.+), shared with partner (.+), passed to dealer (.+)$/, "Comprado $1 (retalho $2, grosso $3). Fica consigo $4, partilhado com o parceiro $5, passado ao revendedor $6"],
  [/^Bought (.+) \(retail (.+), wholesale (.+)\)\. You keep (.+), shared with partner (.+)$/, "Comprado $1 (retalho $2, grosso $3). Fica consigo $4, partilhado com o parceiro $5"],
  [/^Changed to the new (\d+)-digit number$/, "Mudado para o novo número de $1 algarismos"],
  [/^Counted (.+)$/, "Contado $1"],
  [/^Credit (.*\d.*)$/, "Crédito $1"],
  [/^Credit limit (.+) \(suggested\)$/, "Limite de crédito $1 (sugerido)"],
  [/^Credit limit (.+) \(set by you\)$/, "Limite de crédito $1 (definido por si)"],
  [/^Entry (\d+)$/, "Operação $1"],
  [/^Sale (\d+)$/, "Venda $1"],
  [/^(.+) paid (.+) in advance\. It is used on this sale automatically\. (.+) customer\.$/, "$1 pagou $2 adiantado. É usado automaticamente nesta venda. Cliente: $t3."],
  [/^(.+) still has (.+) to pay\. (.+) customer\.$/, "$1 ainda deve $2. Cliente: $t3."],
  [/^(.+) has nothing to pay\. (.+) customer\.$/, "$1 não tem nada a pagar. Cliente: $t2."],
  [/^Filled in from your last record on (.+)\. Change what has moved\.$/, "Preenchido com o último registo de $1. Mude o que mudou."],
  [/^For your safety, the app asks for your password every (\d+) days\.$/, "Por segurança, a aplicação pede a palavra-passe a cada $1 dias."],
  [/^From (.*\d.*)$/, "Desde $1"],
  [/^Working Capital, from (.+)$/, "Capital de exploração, desde $1"],
  [/^You counted on (.+)$/, "Contado em $1"],
  [/^Highest: (.+)$/, "Máximo: $1"],
  [/^Last paid you (\d+) days ago$/, "Pagou-lhe há $1 dias"],
  [/^Has not paid you back in (\d+) days$/, "Não lhe pagou nada há $1 dias"],
  [/^Last used (.+)$/, "Usado em $1"],
  [/^Oldest unpaid sale is (\d+) days old$/, "A venda por pagar mais antiga tem $1 dias"],
  [/^Has not paid for (\d+) days$/, "Não paga há $1 dias"],
  [/^Had money written off before \((.+)\)$/, "Já teve uma perda antes ($1)"],
  [/^Paid late 1 time$/, "Pagou com atraso 1 vez"],
  [/^Paid late (\d+) times$/, "Pagou com atraso $1 vezes"],
  [/^Owes you (.+), which is (\d+)% of the (.+) that all agents owe you$/, "Deve-lhe $1, ou seja $2% dos $3 que todos os agentes lhe devem"],
  [/^Too much depends on one customer: (.+) owes you (.+), which is (\d+)% of the (.+) that all customers owe you\. Think twice before giving them more credit\.$/, "Depende demasiado de um só cliente: $1 deve-lhe $2, ou seja $3% dos $4 que todos os clientes lhe devem. Pense bem antes de lhe dar mais crédito."],
  [/^1 high-risk customer has (.+) to pay$/, "1 cliente de risco elevado deve $1"],
  [/^(\d+) high-risk customers have (.+) to pay$/, "$1 clientes de risco elevado devem $2"],
  [/^1 customer is over their credit limit$/, "1 cliente passou o limite de crédito"],
  [/^(\d+) customers are over their credit limit$/, "$1 clientes passaram o limite de crédito"],
  [/^Money was missing on (\d+) checks? in the last 30 days \((.+) in total\)\. Open Daily Cash Check to see why\.$/, "Faltou dinheiro em $1 verificação(ões) nos últimos 30 dias ($2 no total). Abra a verificação diária de caixa para ver porquê."],
  [/^(.+) has not paid you for (\d+) days and owes you (.+)$/, "$1 não lhe paga há $2 dias e deve-lhe $3"],
  [/^Losses this month: (.+)$/, "Perdas deste mês: $1"],
  [/^Over the credit limit by (.+)$/, "Passou o limite de crédito em $1"],
  [/^(.+) is high risk\. Ask for payment now instead of giving credit\. This goes over their credit limit of (.+)\. They would have (.+) to pay\.$/, "$1 é de risco elevado. Peça o pagamento agora em vez de dar crédito. Isto passa o limite de crédito de $2. Ficaria a dever $3."],
  [/^(.+) is high risk\. Ask for payment now instead of giving credit\.$/, "$1 é de risco elevado. Peça o pagamento agora em vez de dar crédito."],
  [/^This goes over their credit limit of (.+)\. They would have (.+) to pay\.$/, "Isto passa o limite de crédito de $1. Ficaria a dever $2."],
  [/^No Gambian network uses numbers starting with (\d)\. Africell: 2, 4 or 7\. QCell: 3 or 5\. Comium: 6 or 8\. Gamcel: 9\.$/, "Nenhuma rede gambiana tem números a começar por $1. Africell: 2, 4 ou 7. QCell: 3 ou 5. Comium: 6 ou 8. Gamcel: 9."],
  [/^(Africell|QCell|Comium) numbers start with (\d\d) and then (.+)\.$/, "Os números $1 começam por $2 e depois $3."],
  [/^Will be saved as (.+)$/, "Será guardado: $1"],
  [/^To Collect (.*\d.*)$/, "A receber $1"],
  [/^To Pay (.*\d.*)$/, "A pagar $1"],
  [/^To collect (.*\d.*)$/, "A receber $1"],
  [/^to collect (.*\d.*)$/, "a receber $1"],
  [/^to pay (.*\d.*)$/, "a pagar $1"],
  [/^To pay agents: (.+)$/, "A pagar a agentes: $1"],
  [/^(.+) now: (.+)\. After this entry: (.+)\.$/, "$1 agora: $t2. Depois desta operação: $t3."],
  [/^Still to pay (.+)$/, "Ainda por pagar $1"],
  [/^Nothing \(credit (.+)\)$/, "Nada (crédito $1)"],
  [/^Overpaid by (.+)$/, "Pago a mais em $1"],
  [/^Should have (.+), counted (.+)$/, "Deveria ter $1, contado $2"],
  [/^Statement (.+), received (.+), shared with Agent or Partner (.+) \((.+)\)$/, "Extrato $1, recebido $2, partilhado com agente ou parceiro $3 ($4)"],
  [/^Statement (.+), received (.+)$/, "Extrato $1, recebido $2"],
  [/^Show more \((\d+) older\)$/, "Ver mais ($1 mais antigos)"],
  [/^Reference (\S+)\. Recorded (.+?)\. Last changed (.+)\.$/, "Referência $1. Registada em $2. Alterada em $3."],
  [/^Reference (\S+)\. Recorded (.+)\.$/, "Referência $1. Registada em $2."],
  [/^Reference (\S+)\.$/, "Referência $1."],
  [/^Save for (.+)$/, "Guardar ($1)"],
  [/^Saved (\d+) sales$/, "$1 vendas guardadas"],
  [/^Saved 1 sale$/, "1 venda guardada"],
  [/^Saved (\d+) entrys?$/, "$1 operações guardadas"],
  [/^Saved (\d+) entries$/, "$1 operações guardadas"],
  [/^Saved\. (.+) is missing\. Open Daily Cash Check to see why\.$/, "Guardado. Faltam $1. Abra a verificação diária de caixa para ver porquê."],
  [/^Saved\. (.+) extra\. Open Daily Cash Check to see why\.$/, "Guardado. $1 a mais. Abra a verificação diária de caixa para ver porquê."],
  [/^Missing (.*\d.*)$/, "Em falta $1"],
  [/^Extra (.*\d.*)$/, "A mais $1"],
  [/^Welcome, (.+)$/, "Bem-vindo, $1"],
  [/^Unpaid for over (\d+) days$/, "Por pagar há mais de $1 dias"],
  [/^WhatsApp opens a chat with \+(\d+) with your message ready\. Nothing is sent until you press send there\.$/, "O WhatsApp abre uma conversa com +$1 com a mensagem pronta. Nada é enviado até carregar em enviar."],
  [/^Password reset email sent to (.+)\.$/, "E-mail para repor a palavra-passe enviado para $1."],
  [/^Too many wrong tries\. Wait (\d+) seconds\.$/, "Demasiadas tentativas erradas. Espere $1 segundos."],
  [/^(.+) added$/, "$1 adicionado"],
  [/^Credit limit for (.+), in (.+)\. Type 0 for no credit\.\nSuggested: (.+)\. Leave it empty to use the suggestion\.$/, "Limite de crédito para $1, em $2. Escreva 0 para sem crédito.\nSugerido: $3. Deixe vazio para usar a sugestão."],
  [/^How much did they pay now\? \((.+)\)$/, "Quanto pagou agora? ($1)"],
  [/^Restore this file\?\n\nIt has (\d+) sales and (\d+) agent entries\.\n\nIt will REPLACE everything currently in the app, and your online records too\.$/, "Restaurar este ficheiro?\n\nTem $1 vendas e $2 operações de agentes.\n\nVai SUBSTITUIR tudo o que está na aplicação, e também os registos online."],
  [/^Restore this file\?\n\nIt has (\d+) sales and (\d+) agent entries\.\n\nIt will REPLACE everything currently in the app\.$/, "Restaurar este ficheiro?\n\nTem $1 vendas e $2 operações de agentes.\n\nVai SUBSTITUIR tudo o que está na aplicação."],
  [/^Fill in: (.+)\.$/, "Preencha: $l1."],
  [/^From \((.+)\)$/, "De ($1)"],
  [/^To \((.+)\)$/, "Até ($1)"],
  [/^Commission \((.+)\)$/, "Comissão ($1)"],
  [/^Phone language \((.+)\)$/, "Idioma do telemóvel ($1)"],
  [/^Paste the firebaseConfig block from step (\d)$/, "Cole o bloco firebaseConfig do passo $1"],
  [/^Security rules for step (\d)$/, "Regras de segurança para o passo $1"],
  [/^Setup, about (\d+) minutes$/, "Configuração, cerca de $1 minutos"],
  [/^Write Off as Bad Debt \((.+)\)$/, "Dar como perdido ($1)"],
  [/^(\d+) customers? · (\d+) agents?$/, "$1 cliente(s) · $2 agente(s)"],
  [/^1 customer · (\d+) agents?$/, "1 cliente · $1 agente(s)"],
  [/^1 risk alert$/, "1 alerta de risco"],
  [/^(\d+) risk alerts$/, "$1 alertas de risco"],
  [/^(\d+) overdue$/, "$1 em atraso"]
 ]);
I18N.add('pt', { "entries today": "registos hoje", "entry today": "registo hoje", "Unlock Agent & Client Tracker": "Desbloquear Agent & Client Tracker", "Use PIN": "Usar o PIN" });
I18N.add('pt', { "Mobile Money": "Dinheiro móvel", "Banks": "Bancos", "Microfinance": "Microfinanças", "Other Ways": "Outras formas", "Your Own": "Os seus", "Search": "Pesquisar", "Which Bank?": "Qual banco?", "Which Microfinance?": "Qual microfinança?", "Banks and Microfinance": "Bancos e microfinanças" });
I18N.add('pt', { "Backup": "Cópia de segurança", "Help": "Ajuda" });
I18N.add('pt', { "Already saved": "Já guardados" });
I18N.add('pt', { "All customers": "Todos os clientes", "All agents": "Todos os agentes", "Search name or number": "Pesquisar nome ou número", "No match. Close this and type the new name.": "Sem resultados. Feche e escreva o novo nome." });
I18N.add('pt', {
  "Message": "Mensagem", "Record from a Message": "Registar a partir de uma mensagem", "Message from your wallet or bank": "Mensagem da sua carteira ou banco",
  "Paste the SMS or notification here": "Cole aqui o SMS ou a notificação", "Paste the Copied Message": "Colar a mensagem copiada",
  "Copy the message in your SMS or wallet app, then tap Paste. You check the entry before it is saved.": "Copie a mensagem na sua app de SMS ou carteira e toque em Colar. Verifica o registo antes de ser guardado.",
  "Money in": "Entrada de dinheiro", "Money out": "Saída de dinheiro", "Check: in or out?": "Verificar: entrada ou saída?", "No amount found. Type it in the entry.": "Nenhum valor encontrado. Escreva-o no registo.",
  "Number": "Número", "Name": "Nome", "Reference": "Referência", "Fee": "Taxa", "Balance after": "Saldo depois", "When": "Quando", "Record it as": "Registar como",
  "Payment of a Debt": "Pagamento de uma dívida", "New Sale, Paid": "Nova venda, paga", "A customer paid for data, airtime or a deposit": "Um cliente pagou internet, saldo ou um depósito",
  "A customer paying for an earlier sale": "Um cliente a pagar uma venda anterior", "Received from an Agent": "Recebido de um agente", "An agent sent you money or float": "Um agente enviou-lhe dinheiro ou float",
  "Paid to an Agent": "Pago a um agente", "You sent money or float to an agent": "Enviou dinheiro ou float a um agente",
  "You sent money to a customer's wallet or bank": "Enviou dinheiro para a carteira ou banco de um cliente", "Rent, transport, purchases or other spending": "Renda, transporte, compras ou outras despesas",
  "Messages to Record": "Mensagens a registar", "No payment messages are waiting.": "Não há mensagens de pagamento à espera.", "Ignore": "Ignorar", "Record": "Registar", "Ignore All": "Ignorar todas",
  "Ignore all waiting messages?": "Ignorar todas as mensagens à espera?", "Check": "Verificar", "Automatic Recording": "Registo automático", "Turn payment messages into entries": "Transformar mensagens de pagamento em registos",
  "Read payment notifications": "Ler notificações de pagamento",
  "When a message from Wave, Afrimoney, QMoney, APS, your bank or your SMS app shows a payment, the app keeps it ready for you to record with one tap.": "Quando uma mensagem da Wave, Afrimoney, QMoney, APS, do seu banco ou dos seus SMS mostra um pagamento, a app guarda-a pronta para registar com um toque.",
  "Change in Phone Settings": "Alterar nas definições do telefone", "Turn On in Phone Settings": "Ativar nas definições do telefone",
  "Turn on Agent & Client Tracker in the page that opens.": "Ative o Agent & Client Tracker na página que abre.", "Android says \"Restricted setting\"?": "O Android diz \"Definição restrita\"?",
  "Tap Open App Info below, then the ⋮ menu at the top right, then Allow restricted settings. Come back and tap Turn On again.": "Toque em Informações da app abaixo, depois no menu ⋮ no canto superior direito e em Permitir definições restritas. Volte e toque em Ativar outra vez.",
  "Open App Info": "Informações da app", "Alert me": "Avisar-me", "Shows a notification when a payment message is ready to record, even when the app is closed.": "Mostra uma notificação quando uma mensagem de pagamento está pronta a registar, mesmo com a app fechada.",
  "Turn Off Alerts": "Desligar avisos", "Turn On Alerts": "Ligar avisos", "Share a message to the app": "Partilhar uma mensagem com a app",
  "Press and hold a payment SMS or notification, tap Share, then choose Agent & Client Tracker. Or copy it and tap Message on the home screen.": "Toque sem soltar num SMS ou notificação de pagamento, toque em Partilhar e escolha Agent & Client Tracker. Ou copie-a e toque em Mensagem no início.",
  "Fully automatic": "Totalmente automático", "Reading payment notifications by itself needs the Android app.": "Ler notificações de pagamento sozinho precisa da app Android.",
  "Get the Android App": "Obter a app Android", "Record from a Message Now": "Registar a partir de uma mensagem", "Press and hold the box, then tap Paste.": "Toque sem soltar na caixa e depois em Colar.",
  "Messages stay on this phone. Chats such as WhatsApp are never read. You always check an entry before it is saved.": "As mensagens ficam neste telefone. Conversas como o WhatsApp nunca são lidas. Verifica sempre um registo antes de ser guardado."
}, [
  [/^(\d+) messages? to record$/, "$1 mensagem(ns) a registar"], [/^Messages to Record \((\d+)\)$/, "Mensagens a registar ($1)"],
  [/^(.+) is paying what they owe$/, "$1 está a pagar o que deve"], [/^owes (.+)$/, "deve $1"]
]);
