/* Français – made from i18n/*.txt by i18n/build.py. Edit those files, not this one. */
I18N.add('fr', {
"Home": "Accueil",
"Customers": "Clients",
"Agents": "Agents",
"History": "Historique",
"Settings": "Réglages",
"Customer": "Client",
"Agent": "Agent",
"Save": "Enregistrer",
"Save All": "Tout enregistrer",
"Save, Add Another": "Enregistrer et ajouter",
"Close": "Fermer",
"Cancel": "Annuler",
"Delete": "Supprimer",
"Deleted": "Supprimé",
"Edit": "Modifier",
"Back": "Retour",
"Continue": "Continuer",
"Copy": "Copier",
"Copied": "Copié",
"Share": "Partager",
"Remove": "Retirer",
"Remove row": "Retirer la ligne",
"Restore": "Restaurer",
"Saved": "Enregistré",
"Saved. Add the next one.": "Enregistré. Ajoutez le suivant.",
"Today": "Aujourd'hui",
"Yesterday": "Hier",
"Other Date": "Autre date",
"Pick": "Choisir",
"Choose": "Choisir",
"All": "Tout",
"All Time": "Toutes les dates",
"Everything": "Tout",
"Date": "Date",
"Time": "Heure",
"Time (Optional)": "Heure (facultatif)",
"Details": "Détails",
"Description": "Description",
"Notes": "Notes",
"Note": "Note",
"Amount": "Montant",
"Total": "Total",
"Status": "Statut",
"Email": "E-mail",
"Password": "Mot de passe",
"Country": "Pays",
"Currency": "Monnaie",
"Symbol": "Symbole",
"Code": "Code",
"Language": "Langue",
"Language saved": "Langue enregistrée",
"Phone language": "Langue du téléphone",
"Message Language": "Langue du message",
"The app can be used in English, French or Portuguese. This choice is only for this phone. Reminder messages have their own language choice when you send them.": "L'application existe en anglais, en français et en portugais. Ce choix ne concerne que ce téléphone. Les messages de rappel ont leur propre choix de langue au moment de l'envoi.",
"Welcome": "Bienvenue",
"Welcome,": "Bienvenue,",
"Welcome back,": "Bon retour,",
"Sales": "Ventes",
"Sale": "Vente",
"New Sale": "Nouvelle vente",
"Edit Sale": "Modifier la vente",
"Customer Paid": "Paiement client",
"Edit Payment": "Modifier le paiement",
"Agent Entry": "Opération agent",
"Agent Entries": "Opérations agents",
"Agent entries": "Opérations agents",
"New Agent Entry": "Nouvelle opération agent",
"Edit Agent Entry": "Modifier l'opération agent",
"Money Out": "Sorties d'argent",
"Edit Money Out": "Modifier la sortie d'argent",
"Record Balances": "Noter les soldes",
"Change Balances": "Modifier les soldes",
"Record Balances Now": "Noter les soldes maintenant",
"Send Reminder": "Envoyer un rappel",
"Send reminder": "Envoyer un rappel",
"Send a Reminder": "Envoyer un rappel",
"Data / Deposit": "Internet / Dépôt",
"Wallet Exchange": "Échange portefeuille",
"Payments": "Paiements",
"Expenses and Money Out": "Dépenses et sorties d'argent",
"Referral Sales": "Ventes apporteurs",
"Referral sales": "Ventes apporteurs",
"Referral Agents": "Agents apporteurs",
"Commissions": "Commissions",
"Commission": "Commission",
"Daily Cash Check": "Contrôle de caisse du jour",
"Monthly Balance Check": "Contrôle mensuel des soldes",
"Capital Portfolio": "Portefeuille de capital",
"Risk Check": "Contrôle des risques",
"Risk check": "Contrôle des risques",
"Risk": "Risque",
"Losses and Errors": "Pertes et erreurs",
"Sales and Customers": "Ventes et clients",
"Agents and Partners": "Agents et partenaires",
"Money": "Argent",
"Every day, with filters": "Chaque jour, avec des filtres",
"Who might not pay": "Qui risque de ne pas payer",
"On WhatsApp": "Sur WhatsApp",
"Float and deals": "Float et opérations",
"Sales for other agents": "Ventes pour d'autres agents",
"Wallets and EVC": "Portefeuilles et EVC",
"Does your money balance?": "Votre argent est-il juste ?",
"Month by month": "Mois par mois",
"Available and working capital": "Capital disponible et de roulement",
"Write-offs and mistakes": "Pertes et erreurs",
"Money received today": "Argent reçu aujourd'hui",
"Entries today": "Opérations du jour",
"Ready when you are": "Prêt quand vous l'êtes",
"Tap New Sale to record your first sale. Everything you record shows up here.": "Touchez Nouvelle vente pour noter votre première vente. Tout ce que vous notez apparaît ici.",
"To Collect": "À encaisser",
"To Pay": "À payer",
"To collect": "À encaisser",
"To pay": "À payer",
"To Collect from Customers": "À encaisser des clients",
"To Collect from Agents": "À encaisser des agents",
"Paid in Advance": "Payé d'avance",
"Used on their next purchases": "Utilisé sur leurs prochains achats",
"Overdue Sales": "Ventes en retard",
"Commission This Month": "Commission ce mois-ci",
"Losses This Month": "Pertes ce mois-ci",
"Working Capital": "Capital de roulement",
"Tips": "Pourboires",
"Tips (extra income)": "Pourboires (revenu en plus)",
"Tips (inside payments)": "Pourboires (inclus dans les paiements)",
"Tips to Hand Over": "Pourboires à remettre",
"Tips Handed Over": "Pourboires remis",
"Risk alerts": "Alertes de risque",
"Open risk check": "Ouvrir le contrôle des risques",
"Billed": "Facturé",
"Paid": "Payé",
"Biggest amounts to collect": "Plus gros montants à encaisser",
"Chase these first.": "Relancez ceux-ci d'abord.",
"Your customers": "Vos clients",
"Commission by wallet and EVC": "Commission par portefeuille et EVC",
"Regular": "Régulier",
"Irregular": "Irrégulier",
"Inactive (90+ days)": "Inactif (90 jours et plus)",
"Bad (high risk)": "Mauvais (risque élevé)",
"Do not give credit": "Pas de crédit",
"Outstanding": "À payer",
"Overdue": "En retard",
"Overpaid": "Payé en trop",
"Bad debt": "Créance perdue",
"Settled": "Réglé",
"Balanced": "Juste",
"Missing": "Manquant",
"Extra": "En trop",
"First Record": "Premier relevé",
"First record": "Premier relevé",
"Needs balances": "Soldes manquants",
"No opening balances": "Pas de soldes de départ",
"Search name, phone, reference or details": "Chercher un nom, un numéro, une référence ou un détail",
"Search name or phone": "Chercher un nom ou un numéro",
"Search agent, number or reference": "Chercher un agent, un numéro ou une référence",
"Search history": "Chercher dans l'historique",
"Search customers": "Chercher des clients",
"Search agents": "Chercher des agents",
"Payment Status": "Statut du paiement",
"Not Fully Paid": "Pas entièrement payé",
"Paid or Overpaid": "Payé ou payé en trop",
"Paid Through": "Payé par",
"Pick Dates": "Choisir les dates",
"From": "Du",
"To": "Au",
"Agent defaulted": "Agent défaillant",
"Try a different search or filter.": "Essayez une autre recherche ou un autre filtre.",
"Try a different search, day or filter.": "Essayez une autre recherche, un autre jour ou un autre filtre.",
"Customer WhatsApp / Phone": "WhatsApp / téléphone du client",
"Customer Name": "Nom du client",
"Customer name": "Nom du client",
"Customer phone": "Téléphone du client",
"Customer Phone": "Téléphone du client",
"Country of this number": "Pays de ce numéro",
"Date of This Sale": "Date de la vente",
"Date They Paid": "Date du paiement",
"Date of This Entry": "Date de l'opération",
"Date It Was Paid": "Date du paiement",
"Date of These Balances": "Date de ces soldes",
"Date for These Sales": "Date de ces ventes",
"Date for These Entries": "Date de ces opérations",
"Time the Customer Did It": "Heure de la vente",
"Time They Paid": "Heure du paiement",
"Time of the Transaction": "Heure de l'opération",
"Optional. The app also saves the exact moment you recorded the sale.": "Facultatif. L'application enregistre aussi le moment exact où vous avez noté la vente.",
"Optional. The app also saves the exact moment you recorded it.": "Facultatif. L'application enregistre aussi le moment exact où vous l'avez noté.",
"Tap the date of this transaction.": "Touchez la date de cette opération.",
"Exchange Type": "Type d'échange",
"Bundle, Deposit or Details": "Forfait, dépôt ou détails",
"Amount You Sent Out (Optional)": "Montant que vous avez envoyé (facultatif)",
"What you paid out to the customer. It keeps your balance checks accurate.": "Ce que vous avez versé au client. Cela rend vos contrôles de soldes justes.",
"How Was It Paid?": "Comment a-t-il payé ?",
"How was it paid": "Comment a-t-il payé",
"Tap how this sale was paid.": "Touchez comment cette vente a été payée.",
"Paid in Full": "Payé en entier",
"Part Paid": "Payé en partie",
"On Credit": "À crédit",
"Money received": "Argent reçu",
"Some received": "Une partie reçue",
"Nothing yet": "Rien pour l'instant",
"Amount Received So Far": "Montant déjà reçu",
"Amount received so far": "Montant déjà reçu",
"Other (type your own)…": "Autre (à saisir)…",
"Other, type your own": "Autre, à saisir",
"Type it here": "Tapez-le ici",
"Bank Name": "Nom de la banque",
"What the Data or Airtime Cost You (Optional)": "Ce que l'internet ou le crédit vous a coûté (facultatif)",
"Used in your balance checks.": "Utilisé dans vos contrôles de soldes.",
"Tip on Top (Extra Income)": "Pourboire en plus (revenu en plus)",
"Tip Included in the Amount Received": "Pourboire inclus dans le montant reçu",
"Tip to Hand Over (Not Your Income)": "Pourboire à remettre (pas votre revenu)",
"Number That Received the Data or Money (If Different)": "Numéro qui a reçu l'internet ou l'argent (s'il est différent)",
"Date Paid, Only If Paid Later": "Date du paiement, seulement s'il a payé plus tard",
"Saves how many days late they paid.": "Enregistre combien de jours de retard.",
"Reason for Write-Off": "Raison de la perte",
"Only if you will never collect it.": "Seulement si vous ne serez jamais payé.",
"More Details": "Plus de détails",
"Several Sales? Record Them All at Once": "Plusieurs ventes ? Notez-les toutes d'un coup",
"Several Entries? Record Them All at Once": "Plusieurs opérations ? Notez-les toutes d'un coup",
"Several Sales at Once": "Plusieurs ventes d'un coup",
"Several Agent Entries at Once": "Plusieurs opérations agents d'un coup",
"Several Entries at Once": "Plusieurs opérations d'un coup",
"Record several sales at once": "Noter plusieurs ventes d'un coup",
"Type several sales, then save them all at once. The date you choose goes on every row, and you can still change any row's date.": "Tapez plusieurs ventes, puis enregistrez-les toutes d'un coup. La date choisie s'applique à chaque ligne, et vous pouvez encore changer la date de n'importe quelle ligne.",
"Type several entries, then save them all at once. The date you choose goes on every row, and you can still change any row's date.": "Tapez plusieurs opérations, puis enregistrez-les toutes d'un coup. La date choisie s'applique à chaque ligne, et vous pouvez encore changer la date de n'importe quelle ligne.",
"Paid Through, for All Rows": "Payé par, pour toutes les lignes",
"Exchange Type, for All Rows": "Type d'échange, pour toutes les lignes",
"Same as above": "Comme au-dessus",
"Add Another Row": "Ajouter une ligne",
"Add a row": "Ajouter une ligne",
"Type at least one sale.": "Tapez au moins une vente.",
"Type at least one entry.": "Tapez au moins une opération.",
"Amount Paid": "Montant payé",
"Type the amount they paid.": "Tapez le montant qu'il a payé.",
"Still to Pay Now": "Reste à payer maintenant",
"After This Payment": "Après ce paiement",
"New customer: this payment is recorded as credit they can use later.": "Nouveau client : ce paiement est noté comme un crédit qu'il pourra utiliser plus tard.",
"Agent Name": "Nom de l'agent",
"Agent name": "Nom de l'agent",
"Use the same name every time, even if the agent uses another number.": "Utilisez toujours le même nom, même si l'agent utilise un autre numéro.",
"Transaction Type": "Type d'opération",
"Transaction type": "Type d'opération",
"For example: ComCach float, Xpress deposit, GT Bank to Wave.": "Par exemple : float ComCach, dépôt Xpress, GT Bank vers Wave.",
"Paid to Agent": "Payé à l'agent",
"Received from Agent": "Reçu de l'agent",
"Paid to agent": "Payé à l'agent",
"Received from agent": "Reçu de l'agent",
"Number That Received the Service": "Numéro qui a reçu le service",
"The phone number that received the float, credit or service.": "Le numéro qui a reçu le float, le crédit ou le service.",
"Agent WhatsApp / Phone": "WhatsApp / téléphone de l'agent",
"Agent Type": "Type d'agent",
"Regular Agent": "Agent simple",
"Master Agent": "Agent principal",
"Type the amount you paid to the agent, or received from the agent.": "Tapez le montant payé à l'agent ou reçu de l'agent.",
"This Entry": "Cette opération",
"This Sale": "Cette vente",
"Fully paid": "Entièrement payé",
"Referring Agent": "Agent apporteur",
"Service": "Service",
"Data Sending": "Envoi d'internet",
"Deposit": "Dépôt",
"EVC": "EVC",
"Amount (or the Day's Total)": "Montant (ou total de la journée)",
"Commission Rate (%)": "Taux de commission (%)",
"Agent's Share (%)": "Part de l'agent (%)",
"Client Name": "Nom du client",
"Client Phone": "Téléphone du client",
"Agent's Cut": "Part de l'agent",
"You Keep": "Ce que vous gardez",
"New Referral Sale": "Nouvelle vente apporteur",
"Edit Referral Sale": "Modifier la vente apporteur",
"New Wallet Commission": "Nouvelle commission portefeuille",
"Edit Wallet Commission": "Modifier la commission portefeuille",
"Month": "Mois",
"Wallet": "Portefeuille",
"Commission on Statement": "Commission sur le relevé",
"Commission Paid to You": "Commission qui vous a été payée",
"Shared with an Agent or Partner": "Partagé avec un agent ou un partenaire",
"Agent or Partner Name": "Nom de l'agent ou du partenaire",
"Net Commission": "Commission nette",
"New EVC Entry": "Nouvelle entrée EVC",
"Edit EVC Entry": "Modifier l'entrée EVC",
"EVC Operator": "Opérateur EVC",
"Purchase Amount": "Montant de l'achat",
"Part Sold to Other Dealers": "Part vendue à d'autres revendeurs",
"Wholesale. Leave empty if you sold it all to customers.": "En gros. Laissez vide si vous avez tout vendu aux clients.",
"Dealer Name": "Nom du revendeur",
"Operator Commission Rate (%)": "Taux de commission de l'opérateur (%)",
"The percentage the operator gives you on what you buy.": "Le pourcentage que l'opérateur vous donne sur vos achats.",
"Share Paid to Partner on Retail Sales (%)": "Part versée au partenaire sur les ventes au détail (%)",
"Share Paid to Partner on Wholesale (%)": "Part versée au partenaire sur la vente en gros (%)",
"Only if you share part of your commission with a partner or line owner. Otherwise leave it at 0.": "Seulement si vous partagez une partie de votre commission avec un partenaire ou le propriétaire de la ligne. Sinon, laissez 0.",
"Retail Part": "Part au détail",
"Total Commission": "Commission totale",
"Shared with Partner": "Partagé avec le partenaire",
"Passed to Dealer": "Reversé au revendeur",
"What Was It For?": "À quoi a-t-il servi ?",
"Paid From": "Payé depuis",
"Type an amount greater than 0.": "Tapez un montant supérieur à 0.",
"Log an Error": "Noter une erreur",
"Edit Error": "Modifier l'erreur",
"Date Found": "Date de découverte",
"Type of Error": "Type d'erreur",
"What Happened": "Ce qui s'est passé",
"Did It Cost Money?": "Cela a-t-il coûté de l'argent ?",
"Amount Lost": "Montant perdu",
"Caused By": "Causé par",
"Found By": "Trouvé par",
"How It Was Fixed": "Comment ce fut corrigé",
"Date Fixed": "Date de correction",
"Open": "Ouvert",
"In Progress": "En cours",
"Fixed": "Corrigé",
"Yes": "Oui",
"No": "Non",
"Record a Payment on This Sale": "Noter un paiement sur cette vente",
"Payment recorded": "Paiement noté",
"Delete this entry? This cannot be undone.": "Supprimer cette opération ? C'est définitif.",
"Total You Counted": "Total que vous avez compté",
"You Should Have": "Vous devriez avoir",
"Difference": "Différence",
"None, it balances": "Aucune, c'est juste",
"This is your first record. The next one will be checked against it.": "C'est votre premier relevé. Le suivant sera comparé à celui-ci.",
"Add Another Account or Wallet": "Ajouter un compte ou un portefeuille",
"Name of the new account or wallet. For example: a bank, a new wallet, or money kept at home.": "Nom du nouveau compte ou portefeuille. Par exemple : une banque, un nouveau portefeuille ou l'argent gardé à la maison.",
"That account is already in the list.": "Ce compte est déjà dans la liste.",
"Saved. Your money balances.": "Enregistré. Votre argent est juste.",
"Saved. This is your starting point for the next check.": "Enregistré. C'est votre point de départ pour le prochain contrôle.",
"Cash": "Espèces",
"Cash in Hand": "Espèces en main",
"Bank": "Banque",
"Bank Transfer": "Virement bancaire",
"EVC Stock": "Stock EVC",
"Bank-to-Wallet": "Banque vers portefeuille",
"Wallet-to-Bank": "Portefeuille vers banque",
"Wallet-to-Wallet": "Portefeuille vers portefeuille",
"Bank to Wallet Exchange": "Échange banque vers portefeuille",
"Wallet to Bank Exchange": "Échange portefeuille vers banque",
"Bank to Bank Exchange": "Échange banque vers banque",
"Float Transfer/Rebalancing (between wallets)": "Transfert/rééquilibrage de float (entre portefeuilles)",
"EVC/Voucher Transaction": "Opération EVC/bon",
"Data / Airtime Purchase": "Achat d'internet / de crédit",
"Rent": "Loyer",
"Transport": "Transport",
"Staff": "Personnel",
"Bank Charges": "Frais bancaires",
"Owner Withdrawal": "Retrait du propriétaire",
"Other": "Autre",
"Business decision (waived)": "Décision commerciale (abandon)",
"Customer unreachable/disappeared": "Client injoignable ou disparu",
"Fraud/Scam": "Fraude/arnaque",
"Error-caused loss": "Perte due à une erreur",
"Wrong amount charged": "Mauvais montant facturé",
"Wrong customer/agent billed": "Mauvais client ou agent facturé",
"Duplicate entry": "Opération en double",
"Wrong exchange rate": "Mauvais taux de change",
"Wrong data bundle": "Mauvais forfait internet",
"Reconciliation mismatch": "Écart de rapprochement",
"Owner/Staff": "Propriétaire/personnel",
"System/Technical": "Système/technique",
"Unclear": "Pas clair",
"Gambia": "Gambie",
"Senegal": "Sénégal",
"Guinea": "Guinée",
"Mali": "Mali",
"Guinea-Bissau": "Guinée-Bissau",
"Sierra Leone": "Sierra Leone",
"Liberia": "Liberia",
"Ghana": "Ghana",
"Nigeria": "Nigeria",
"Côte d'Ivoire": "Côte d'Ivoire",
"Burkina Faso": "Burkina Faso",
"Togo": "Togo",
"Benin": "Bénin",
"Niger": "Niger",
"Mauritania": "Mauritanie",
"Cabo Verde": "Cap-Vert",
"Morocco": "Maroc",
"Algeria": "Algérie",
"Tunisia": "Tunisie",
"Egypt": "Égypte",
"Cameroon": "Cameroun",
"DR Congo": "RD Congo",
"Congo": "Congo",
"Gabon": "Gabon",
"Kenya": "Kenya",
"Uganda": "Ouganda",
"Tanzania": "Tanzanie",
"Rwanda": "Rwanda",
"Ethiopia": "Éthiopie",
"South Africa": "Afrique du Sud",
"United States": "États-Unis",
"Canada": "Canada",
"United Kingdom": "Royaume-Uni",
"France": "France",
"Germany": "Allemagne",
"Spain": "Espagne",
"Italy": "Italie",
"Netherlands": "Pays-Bas",
"Belgium": "Belgique",
"Portugal": "Portugal",
"Türkiye": "Turquie",
"Saudi Arabia": "Arabie saoudite",
"United Arab Emirates": "Émirats arabes unis",
"India": "Inde",
"Pakistan": "Pakistan",
"China": "Chine",
"Brazil": "Brésil",
"Australia": "Australie",
"Classic": "Classique",
"Create account": "Créer un compte",
"Sign in": "Se connecter",
"This phone only": "Ce téléphone seulement",
"Your name or business name": "Votre nom ou celui de votre commerce",
"Your Name or Business Name": "Votre nom ou celui de votre commerce",
"Password, at least 6 characters": "Mot de passe, au moins 6 caractères",
"Create my account": "Créer mon compte",
"By continuing you accept the": "En continuant, vous acceptez la",
"privacy policy": "politique de confidentialité",
"Forgot password?": "Mot de passe oublié ?",
"Your records stay only on this phone. You can create an account later to keep them online.": "Vos données restent uniquement sur ce téléphone. Vous pourrez créer un compte plus tard pour les garder en ligne.",
"Start using the app": "Commencer",
"Record data sales, wallet transfers and agent deals. Track every debt. Works without internet.": "Notez les ventes d'internet, les transferts de portefeuille et les opérations avec les agents. Suivez chaque dette. Fonctionne sans internet.",
"Record data sales, deposits and wallet transfers": "Notez les ventes d'internet, les dépôts et les transferts",
"Track agent deals and float, both ways": "Suivez les opérations et le float avec les agents, dans les deux sens",
"See who owes you and who might not pay": "Voyez qui vous doit et qui risque de ne pas payer",
"Check that your money balances every day": "Vérifiez chaque jour que votre argent est juste",
"You are offline. You can use the app on this phone now and create an account later.": "Vous êtes hors ligne. Vous pouvez utiliser l'application sur ce téléphone et créer un compte plus tard.",
"Connecting…": "Connexion…",
"Tell us who this account belongs to. Your name appears on your home screen.": "Dites-nous à qui appartient ce compte. Votre nom apparaît sur l'écran d'accueil.",
"Sets your currency and how phone numbers are checked. You can change them later.": "Définit votre monnaie et la façon de vérifier les numéros. Vous pourrez les changer plus tard.",
"Skip for now": "Plus tard",
"I have a backup file to restore": "J'ai une sauvegarde à restaurer",
"Type your name or business name.": "Tapez votre nom ou celui de votre commerce.",
"Type your name or business name, or tap Skip for now.": "Tapez votre nom ou celui de votre commerce, ou touchez Plus tard.",
"Type your email and a password.": "Tapez votre e-mail et un mot de passe.",
"Type your email and password.": "Tapez votre e-mail et votre mot de passe.",
"Type your email address.": "Tapez votre adresse e-mail.",
"Type your email first.": "Tapez d'abord votre e-mail.",
"Type a password.": "Tapez un mot de passe.",
"Creating your account…": "Création de votre compte…",
"Choose a PIN": "Choisissez un code PIN",
"Protect your records. Choose 4 to 6 digits that only you know.": "Protégez vos données. Choisissez 4 à 6 chiffres que vous seul connaissez.",
"Type the PIN again": "Tapez le code PIN encore une fois",
"Type the same PIN once more.": "Tapez le même code PIN une seconde fois.",
"The two PINs did not match. Start again.": "Les deux codes ne sont pas pareils. Recommencez.",
"Next": "Suivant",
"Not now": "Pas maintenant",
"The PIN is required while you are signed in to an account.": "Le code PIN est obligatoire quand vous êtes connecté à un compte.",
"Use your fingerprint too?": "Utiliser aussi votre empreinte ?",
"Open the app with your fingerprint or face. Your PIN always works as a back-up.": "Ouvrez l'application avec votre empreinte ou votre visage. Le code PIN marche toujours en secours.",
"Use Fingerprint": "Utiliser l'empreinte",
"Your PIN is on": "Votre code PIN est activé",
"Enter your PIN to open your records": "Tapez votre code PIN pour ouvrir vos données",
"Wrong PIN. Try again.": "Code PIN incorrect. Réessayez.",
"Forgot PIN?": "Code PIN oublié ?",
"Forgot your PIN?": "Code PIN oublié ?",
"Use Fingerprint or Face": "Utiliser l'empreinte ou le visage",
"Fingerprint did not work. Type your PIN.": "L'empreinte n'a pas marché. Tapez votre code PIN.",
"Type your account password. Then you can choose a new PIN.": "Tapez le mot de passe de votre compte. Ensuite vous pourrez choisir un nouveau code PIN.",
"Reset My PIN": "Changer mon code PIN",
"Your password is right. Choose a new PIN.": "Votre mot de passe est bon. Choisissez un nouveau code PIN.",
"You do not have an account, so there is no way to prove who you are. Your records are only on this phone.": "Vous n'avez pas de compte, il n'y a donc aucun moyen de prouver qui vous êtes. Vos données sont seulement sur ce téléphone.",
"If you saved a backup, you can erase this phone, start over and restore the backup. Anything not in a backup will be lost.": "Si vous avez une sauvegarde, vous pouvez tout effacer sur ce téléphone, recommencer et restaurer la sauvegarde. Ce qui n'est pas sauvegardé sera perdu.",
"Erase This Phone and Start Over": "Tout effacer et recommencer",
"Erase everything on this phone and start over? Records that are only on this phone, and not in a backup, will be lost for good.": "Tout effacer sur ce téléphone et recommencer ? Les données qui sont seulement sur ce téléphone, et pas dans une sauvegarde, seront perdues pour toujours.",
"Last check: erase all records on this phone?": "Dernière vérification : effacer toutes les données de ce téléphone ?",
"Please sign in again": "Merci de vous reconnecter",
"Type your password.": "Tapez votre mot de passe.",
"Checking…": "Vérification…",
"Sign out": "Se déconnecter",
"Too many tries. Wait a few minutes, then try again.": "Trop d'essais. Attendez quelques minutes puis réessayez.",
"Wrong email or password.": "E-mail ou mot de passe incorrect.",
"An account with this email already exists. Tap Sign in instead.": "Un compte existe déjà avec cet e-mail. Touchez Se connecter.",
"No account with this email. Tap Create account first.": "Aucun compte avec cet e-mail. Touchez d'abord Créer un compte.",
"That email address does not look right.": "Cette adresse e-mail ne semble pas correcte.",
"Use a password of at least 6 characters.": "Utilisez un mot de passe d'au moins 6 caractères.",
"No internet connection. Try again when you are online.": "Pas de connexion internet. Réessayez quand vous serez en ligne.",
"That password belongs to a different account.": "Ce mot de passe correspond à un autre compte.",
"For your safety, type your password again, then try once more.": "Pour votre sécurité, retapez votre mot de passe, puis réessayez.",
"Something went wrong.": "Un problème est survenu.",
"Sign in first.": "Connectez-vous d'abord.",
"Cannot reach Firebase right now. Your changes are kept and will sync later.": "Impossible de joindre le serveur pour le moment. Vos changements sont gardés et seront envoyés plus tard.",
"Still connecting to Firebase. Check your internet, then try again.": "Connexion au serveur en cours. Vérifiez votre internet, puis réessayez.",
"Account created. Uploading your records.": "Compte créé. Envoi de vos données.",
"Signed in. Bringing in your records.": "Connecté. Récupération de vos données.",
"This phone was removed from the account.": "Ce téléphone a été retiré du compte.",
"Synced": "Synchronisé",
"Syncing": "Synchronisation",
"Offline": "Hors ligne",
"Sign in to sync": "Se connecter pour synchroniser",
"Connecting": "Connexion",
"Sync not reachable": "Synchronisation injoignable",
"Sync problem": "Problème de synchronisation",
"Android phone": "Téléphone Android",
"Windows computer": "Ordinateur Windows",
"Linux computer": "Ordinateur Linux",
"Phone": "Téléphone",
"Account and Security": "Compte et sécurité",
"Your Account": "Votre compte",
"Security": "Sécurité",
"Look and Money": "Apparence et argent",
"Country, Currency and Theme": "Pays, monnaie et couleurs",
"Money Rules": "Règles d'argent",
"Tips and how you record payments": "Pourboires et façon de noter les paiements",
"Your Choices": "Vos listes",
"Payment channels, wallets, EVC operators and other lists": "Moyens de paiement, portefeuilles, opérateurs EVC et autres listes",
"Your Data": "Vos données",
"Your data": "Vos données",
"Backup and Restore": "Sauvegarde et restauration",
"Save a copy of your records": "Gardez une copie de vos données",
"Privacy Policy": "Politique de confidentialité",
"Privacy policy": "Politique de confidentialité",
"How your records are protected": "Comment vos données sont protégées",
"How It Works": "Mode d'emploi",
"Balances, credit, tips, statuses": "Soldes, crédit, pourboires, statuts",
"Lock the App Now": "Verrouiller maintenant",
"Your Details": "Vos informations",
"Sign in to keep records online": "Connectez-vous pour garder vos données en ligne",
"Protect your records with a PIN": "Protégez vos données avec un code PIN",
"PIN and fingerprint on": "Code PIN et empreinte activés",
"PIN on": "Code PIN activé",
"Add your name": "Ajoutez votre nom",
"App Lock": "Verrouillage",
"On": "Activé",
"Off": "Désactivé",
"The app asks for your PIN every time it opens or comes back from another app.": "L'application demande votre code PIN à chaque ouverture et à chaque retour depuis une autre application.",
"Without a lock, anyone who picks up your phone can open your records.": "Sans verrouillage, n'importe qui peut ouvrir vos données en prenant votre téléphone.",
"Set a PIN": "Choisir un code PIN",
"Change PIN": "Changer le code PIN",
"Turn Off": "Désactiver",
"Turn off the PIN? Anyone who picks up your phone will be able to open your records.": "Désactiver le code PIN ? N'importe qui pourra ouvrir vos données en prenant votre téléphone.",
"PIN turned off": "Code PIN désactivé",
"Type your current PIN": "Tapez votre code PIN actuel",
"Fingerprint or Face": "Empreinte ou visage",
"Turn On Fingerprint": "Activer l'empreinte",
"Turn Off Fingerprint": "Désactiver l'empreinte",
"Fingerprint is on": "L'empreinte est activée",
"Fingerprint is off": "L'empreinte est désactivée",
"Could not turn on fingerprint on this phone.": "Impossible d'activer l'empreinte sur ce téléphone.",
"Could not turn on fingerprint. Your PIN still works.": "Impossible d'activer l'empreinte. Votre code PIN marche toujours.",
"This phone or browser does not offer fingerprint unlock for the app.": "Ce téléphone ou ce navigateur ne propose pas le déverrouillage par empreinte pour l'application.",
"Lock Automatically": "Verrouillage automatique",
"Right away": "Tout de suite",
"Only when I lock it": "Seulement quand je verrouille",
"Never": "Jamais",
"How long the app can be out of sight before it asks for your PIN again.": "Combien de temps l'application peut rester cachée avant de redemander votre code PIN.",
"Hide Amounts": "Cacher les montants",
"Hide amounts": "Cacher les montants",
"Show Amounts": "Afficher les montants",
"Show amounts": "Afficher les montants",
"Blur money amounts on screen so people nearby cannot read them. You can also tap the eye at the top of any screen.": "Floute les montants à l'écran pour que les gens autour ne puissent pas les lire. Vous pouvez aussi toucher l'œil en haut de chaque écran.",
"Ask for Your Password Again": "Redemander votre mot de passe",
"After this many days the app asks for your email password again, even with the PIN.": "Après ce nombre de jours, l'application redemande le mot de passe de votre compte, même avec le code PIN.",
"Your Devices": "Vos appareils",
"Every phone that signs in to your account is listed here. If you see one you do not know, remove it and change your password.": "Chaque téléphone connecté à votre compte apparaît ici. Si vous en voyez un que vous ne connaissez pas, retirez-le et changez votre mot de passe.",
"This Phone": "Ce téléphone",
"No devices to show yet.": "Aucun appareil à afficher pour l'instant.",
"Remove this phone from your account? It is signed out the next time it connects.": "Retirer ce téléphone de votre compte ? Il sera déconnecté à sa prochaine connexion.",
"Phone removed": "Téléphone retiré",
"Could not remove it.": "Impossible de le retirer.",
"A new phone signed in to your account.": "Un nouveau téléphone s'est connecté à votre compte.",
"Review": "Vérifier",
"It Was Me": "C'était moi",
"What Protects Your Records": "Ce qui protège vos données",
"Your records are saved on this phone and, if you have an account, in your private online account that only you can open. The PIN and fingerprint stop other people from opening the app on your phone.": "Vos données sont enregistrées sur ce téléphone et, si vous avez un compte, dans votre compte privé en ligne que vous seul pouvez ouvrir. Le code PIN et l'empreinte empêchent les autres d'ouvrir l'application sur votre téléphone.",
"Note: a text-message code for every new phone needs Firebase's paid plan. Until then, new phones are protected by your password, and you see every device here.": "À noter : un code par SMS pour chaque nouveau téléphone demande l'offre payante de Firebase. En attendant, les nouveaux téléphones sont protégés par votre mot de passe, et vous voyez chaque appareil ici.",
"Colour Theme": "Couleurs",
"Classic suits everyone. The country themes use that country's flag colours. Red always means money to collect, and green always means money received.": "Classique convient à tous. Les thèmes des pays utilisent les couleurs du drapeau. Le rouge veut toujours dire argent à encaisser, et le vert argent reçu.",
"Your country decides how phone numbers are checked. Contacts in other countries can still be recorded: choose their country next to the phone box.": "Votre pays décide comment les numéros sont vérifiés. Vous pouvez quand même noter des contacts d'autres pays : choisissez leur pays à côté du numéro.",
"Use This Country's Currency and Colours": "Utiliser la monnaie et les couleurs de ce pays",
"Country, currency and colours updated": "Pays, monnaie et couleurs mis à jour",
"Save Currency": "Enregistrer la monnaie",
"Currency saved": "Monnaie enregistrée",
"Type a currency symbol of up to 8 characters.": "Tapez un symbole de monnaie de 8 caractères au plus.",
"Also use this country's currency and colours": "Utiliser aussi la monnaie et les couleurs de ce pays",
"How Do You Handle Tips?": "Que faites-vous des pourboires ?",
"Extra money on top": "De l'argent en plus",
"Included in the amount received": "Inclus dans le montant reçu",
"Not mine, I hand it over": "Pas à moi, je le remets",
"Tips belong to staff or someone else. They count as money received, but show as Tips to Hand Over and not as your income.": "Les pourboires appartiennent au personnel ou à quelqu'un d'autre. Ils comptent comme argent reçu, mais apparaissent comme Pourboires à remettre et non comme votre revenu.",
"Tips always show on your home screen and are never lost, whichever way you choose.": "Les pourboires s'affichent toujours sur l'accueil et ne sont jamais perdus, quel que soit votre choix.",
"Tip rule saved": "Règle des pourboires enregistrée",
"How Do You Record Sales?": "Comment notez-vous les ventes ?",
"Ask me every time": "Me demander à chaque fois",
"Recommended. You choose Paid in Full, Part Paid or On Credit for each sale, so it is never recorded by mistake.": "Recommandé. Vous choisissez Payé en entier, Payé en partie ou À crédit pour chaque vente, donc rien n'est noté par erreur.",
"Mostly paid on the spot": "Surtout payé sur place",
"Paid in Full is pre-selected on new sales. You still see it clearly and can change it.": "Payé en entier est présélectionné pour les nouvelles ventes. Vous le voyez bien et pouvez le changer.",
"Mostly on credit (debt recording)": "Surtout à crédit (suivi des dettes)",
"On Credit is pre-selected on new sales. Use this if you mainly record who owes you.": "À crédit est présélectionné pour les nouvelles ventes. Choisissez ceci si vous notez surtout qui vous doit.",
"Change the choices that appear in your forms. Put one item on each line. You can add your own, for example another wallet or EVC operator.": "Changez les choix qui apparaissent dans vos formulaires. Une ligne par élément. Vous pouvez ajouter les vôtres, par exemple un autre portefeuille ou opérateur EVC.",
"Payment Channels": "Moyens de paiement",
"Commission Wallets": "Portefeuilles à commission",
"EVC Operators": "Opérateurs EVC",
"Capital and Cash Accounts": "Comptes de capital et de caisse",
"Money Out Categories": "Types de sorties d'argent",
"Wallet Exchange Types": "Types d'échange portefeuille",
"Agent Transaction Types": "Types d'opérations agents",
"Write-Off Reasons": "Raisons des pertes",
"Error Types": "Types d'erreurs",
"Who Caused an Error": "Qui a causé une erreur",
"Save My Choices": "Enregistrer mes listes",
"Your choices are saved": "Vos listes sont enregistrées",
"Keep your records online": "Gardez vos données en ligne",
"Create an account or sign in to keep your records online and on any phone. Records already on this phone are added to your account.": "Créez un compte ou connectez-vous pour garder vos données en ligne et sur n'importe quel téléphone. Les données déjà sur ce téléphone sont ajoutées à votre compte.",
"Create Account": "Créer un compte",
"Sign In": "Se connecter",
"Signed in as": "Connecté en tant que",
"Changes waiting to go online": "Changements en attente d'envoi",
"Last synced": "Dernière synchronisation",
"Sync now": "Synchroniser",
"Changes are saved on this phone first, then sent to your account in the background. Signing out removes your records from this phone; they come back when you sign in again.": "Les changements sont d'abord enregistrés sur ce téléphone, puis envoyés à votre compte. Si vous vous déconnectez, vos données sont retirées de ce téléphone ; elles reviennent quand vous vous reconnectez.",
"Sign out? Your records are removed from this phone and come back when you sign in again.": "Se déconnecter ? Vos données sont retirées de ce téléphone et reviennent quand vous vous reconnectez.",
"Sign out? Your records stay on this phone, but stop syncing until you sign in again.": "Se déconnecter ? Vos données restent sur ce téléphone, mais ne sont plus synchronisées jusqu'à votre reconnexion.",
"Delete account": "Supprimer le compte",
"Delete my account and records": "Supprimer mon compte et mes données",
"This permanently deletes your account and all your records, online and on this phone. It cannot be undone.": "Ceci supprime pour toujours votre compte et toutes vos données, en ligne et sur ce téléphone. C'est définitif.",
"This permanently deletes your account and every record in it, online and on this phone.": "Ceci supprime pour toujours votre compte et toutes ses données, en ligne et sur ce téléphone.",
"Type your password to confirm": "Tapez votre mot de passe pour confirmer",
"Delete everything": "Tout supprimer",
"Last check: delete your account and every record for good?": "Dernière vérification : supprimer pour toujours votre compte et toutes vos données ?",
"Your account and records were deleted": "Votre compte et vos données ont été supprimés",
"Send Me a Password Reset Email": "M'envoyer un e-mail pour changer le mot de passe",
"This app already has its online account built in.": "Cette application a déjà son compte en ligne intégré.",
"Back up": "Sauvegarder",
"You have not saved a backup yet. Your records only live on this phone.": "Vous n'avez pas encore fait de sauvegarde. Vos données sont seulement sur ce téléphone.",
"You have not saved a backup yet.": "Vous n'avez pas encore fait de sauvegarde.",
"Your records live only on this phone.": "Vos données sont seulement sur ce téléphone.",
"If the phone is lost, or the app's data is cleared, they are gone unless you have a backup. Save one at least once a week and keep a copy off the phone, for example on Google Drive or sent to yourself on WhatsApp. Or create an account in Settings, then Your Account.": "Si le téléphone est perdu, ou si les données de l'application sont effacées, elles sont perdues sans sauvegarde. Faites-en une au moins une fois par semaine et gardez une copie hors du téléphone, par exemple sur Google Drive ou envoyée à vous-même sur WhatsApp. Ou créez un compte dans Réglages, puis Votre compte.",
"Last backup": "Dernière sauvegarde",
"Save backup to phone": "Enregistrer la sauvegarde sur le téléphone",
"Send backup to Drive or WhatsApp": "Envoyer la sauvegarde sur Drive ou WhatsApp",
"Backup saved": "Sauvegarde enregistrée",
"Restore from a backup file": "Restaurer depuis une sauvegarde",
"Use this to bring back a backup, or to move your records to a new phone. It replaces everything currently in the app.": "Pour récupérer une sauvegarde, ou passer vos données sur un nouveau téléphone. Cela remplace tout ce qui est dans l'application.",
"Records restored": "Données restaurées",
"That file is not a backup from this app.": "Ce fichier n'est pas une sauvegarde de cette application.",
"Spreadsheet": "Tableur",
"Download all sales as a spreadsheet file that opens in Excel.": "Téléchargez toutes les ventes dans un fichier qui s'ouvre avec Excel.",
"Download sales for Excel": "Télécharger les ventes pour Excel",
"Not saved: your phone storage may be full.": "Non enregistré : la mémoire du téléphone est peut-être pleine.",
"Everything stays on this phone and works without internet. Back it up every week from Settings, then Backup and Restore.": "Tout reste sur ce téléphone et marche sans internet. Sauvegardez chaque semaine depuis Réglages, puis Sauvegarde et restauration.",
"If you want to keep a copy, save a backup first in Settings, then Backup and Restore.": "Si vous voulez garder une copie, faites d'abord une sauvegarde dans Réglages, puis Sauvegarde et restauration.",
"Agent & Client Tracker · Your records are private to you.": "Agent & Client Tracker · Vos données ne sont visibles que par vous.",
"To collect and to pay": "À encaisser et à payer",
"\"To collect\" is money someone must still pay you. \"To pay\" is money you must still pay someone. \"Credit\" means a customer paid you in advance.": "« À encaisser » est l'argent qu'on doit encore vous payer. « À payer » est l'argent que vous devez encore payer. « Crédit » veut dire qu'un client vous a payé d'avance.",
"Choosing the date": "Choisir la date",
"New entries have no date until you tap Today, Yesterday or Other date, so a past sale is never saved with today's date by mistake. The Save button shows the date you chose.": "Les nouvelles opérations n'ont pas de date tant que vous ne touchez pas Aujourd'hui, Hier ou Autre date : une vente passée n'est donc jamais notée par erreur à la date du jour. Le bouton Enregistrer affiche la date choisie.",
"Phone numbers": "Numéros de téléphone",
"Each customer gets a risk score from what they owe, how long it has been unpaid, late payments and write-offs. Low risk can get credit up to their limit; High risk should pay on the spot. You can change any customer's credit limit.": "Chaque client reçoit une note de risque selon ce qu'il doit, depuis combien de temps, ses retards et ses pertes passées. Risque faible : crédit possible jusqu'à sa limite ; risque élevé : il doit payer sur place. Vous pouvez changer la limite de crédit de chaque client.",
"\"Paid to Agent\" is money or float you sent to the agent. \"Received from Agent\" is what they sent you. If you paid more than you received, it shows as To Collect. If you received more, it shows as To Pay.": "« Payé à l'agent » est l'argent ou le float que vous lui avez envoyé. « Reçu de l'agent » est ce qu'il vous a envoyé. Si vous avez payé plus que reçu, cela apparaît dans À encaisser. Si vous avez reçu plus, dans À payer.",
"\"Paid to Agent\" is money or float you sent to them. \"Received from Agent\" is money they sent to you. \"To Collect\" means they must pay you; \"To Pay\" means you must pay them.": "« Payé à l'agent » est l'argent ou le float que vous lui avez envoyé. « Reçu de l'agent » est l'argent qu'il vous a envoyé. « À encaisser » : il doit vous payer ; « À payer » : vous devez le payer.",
"Recording quickly": "Noter vite",
"For every sale you choose Paid in Full, Part Paid or On Credit, so nothing is recorded as paid by mistake. \"Save, Add Another\" keeps the form open with the same date. Use \"Customer Paid\" when someone pays off what they owe without buying anything, and \"Several Sales at Once\" to type many sales together.": "Pour chaque vente vous choisissez Payé en entier, Payé en partie ou À crédit : rien n'est noté comme payé par erreur. « Enregistrer et ajouter » garde le formulaire ouvert avec la même date. Utilisez « Paiement client » quand quelqu'un règle sa dette sans rien acheter, et « Plusieurs ventes d'un coup » pour taper beaucoup de ventes ensemble.",
"Paying an old debt late": "Payer une vieille dette en retard",
"Open the old sale and tap \"Record a payment\", or put the full amount on the new sale. A payment covers its own sale first, and anything extra pays off the oldest unpaid sales. Either way the old sale turns Paid and the app records how many days late it was paid.": "Ouvrez l'ancienne vente et touchez « Noter un paiement », ou mettez tout le montant sur la nouvelle vente. Un paiement règle d'abord sa propre vente, et le surplus paie les ventes impayées les plus anciennes. Dans les deux cas, l'ancienne vente passe à Payé et l'application note le nombre de jours de retard.",
"Paying in advance": "Payer d'avance",
"Nothing extra to do. If a customer overpaid before, their next sale is covered automatically, even if they pay nothing that day. If the credit only covers part of it, the account shows just what is left.": "Rien de plus à faire. Si un client a payé en trop avant, sa vente suivante est couverte automatiquement, même s'il ne paie rien ce jour-là. Si le crédit n'en couvre qu'une partie, le compte affiche juste ce qui reste.",
"Statuses": "Statuts",
"Customer types": "Types de clients",
"Commission = purchase x operator rate. Shared with Partner = retail part x your partner's retail share, plus wholesale part x their wholesale share. On the wholesale part, the rest goes to the dealer.": "Commission = achat x taux de l'opérateur. Partagé avec le partenaire = part au détail x part du partenaire au détail, plus part en gros x sa part en gros. Sur la part en gros, le reste va au revendeur.",
"Record what you have in every wallet, bank and your cash drawer. The app compares it with what you should have: your last balances, plus money in, minus money out. A difference of zero means no money is missing.": "Notez ce que vous avez dans chaque portefeuille, en banque et dans votre caisse. L'application compare avec ce que vous devriez avoir : vos derniers soldes, plus les entrées, moins les sorties. Une différence de zéro veut dire qu'il ne manque rien.",
"Record your balances once to begin. From the second time, the app checks that your money adds up.": "Notez vos soldes une première fois pour commencer. Dès la deuxième fois, l'application vérifie que votre argent est juste.",
"Tap the green button to record your balances.": "Touchez le bouton vert pour noter vos soldes.",
"How It Adds Up": "Le calcul",
"Balances You Recorded": "Soldes que vous avez notés",
"+ Payments from customers": "+ Paiements des clients",
"+ Tips": "+ Pourboires",
"+ Received from agents": "+ Reçu des agents",
"− Paid to agents": "− Payé aux agents",
"− Expenses and money out": "− Dépenses et sorties d'argent",
"You should have": "Vous devriez avoir",
"You counted": "Vous avez compté",
"Change These Balances": "Modifier ces soldes",
"This record may have been removed.": "Ce relevé a peut-être été supprimé.",
"For each month: your balances at the start, plus money in, minus money out, is what you should have at the end. This is compared with the balances you recorded. It does not need a bank statement.": "Pour chaque mois : vos soldes au début, plus les entrées, moins les sorties, donnent ce que vous devriez avoir à la fin. On compare avec les soldes que vous avez notés. Pas besoin de relevé bancaire.",
"Months appear here as you record sales and balances.": "Les mois apparaissent ici quand vous notez des ventes et des soldes.",
"Record your balances at the end of this month to check it.": "Notez vos soldes à la fin de ce mois pour le vérifier.",
"Record your balances at the start of the month too, so the app can check this month.": "Notez aussi vos soldes au début du mois, pour que l'application puisse vérifier ce mois.",
"Record your balances": "Notez vos soldes",
"Record money that left your business: data or airtime you bought, rent, transport, withdrawals. These make your Daily Cash Check and Monthly Balance Check accurate.": "Notez l'argent sorti de votre commerce : internet ou crédit acheté, loyer, transport, retraits. Cela rend justes vos contrôles de caisse et mensuels.",
"Tap the red button to record money out.": "Touchez le bouton rouge pour noter une sortie d'argent.",
"Record your balances whenever you like. Money to collect and money to pay always use today's live totals. The same balances are used for your Daily Cash Check.": "Notez vos soldes quand vous voulez. L'argent à encaisser et à payer utilise toujours les totaux du jour. Les mêmes soldes servent au contrôle de caisse du jour.",
"Available Capital": "Capital disponible",
"Available capital": "Capital disponible",
"Available capital, plus money to collect, minus money to pay": "Capital disponible, plus l'argent à encaisser, moins l'argent à payer",
"From customers and agents": "Des clients et des agents",
"To agents, plus what customers paid in advance": "Aux agents, plus ce que les clients ont payé d'avance",
"Your Recorded Balances": "Vos soldes notés",
"High risk customers": "Clients à risque élevé",
"Medium risk customers": "Clients à risque moyen",
"Money at risk": "Argent à risque",
"To collect from medium and high risk customers": "À encaisser auprès des clients à risque moyen et élevé",
"Warnings": "Alertes",
"No warnings right now.": "Aucune alerte pour le moment.",
"No customer has money to pay. Well done.": "Aucun client n'a d'argent à payer. Bravo.",
"Agents with money to pay you": "Agents qui ont de l'argent à vous payer",
"How the risk score works": "Comment la note de risque est calculée",
"Suggested credit: Low risk regular customers up to two of their usual purchases; other Low risk customers one; Medium risk one; High risk none. Tap \"Set credit limit\" to choose your own.": "Crédit conseillé : clients réguliers à faible risque, jusqu'à deux achats habituels ; autres clients à faible risque, un ; risque moyen, un ; risque élevé, aucun. Touchez « Fixer la limite de crédit » pour choisir vous-même.",
"Set credit limit": "Fixer la limite de crédit",
"Set Credit Limit": "Fixer la limite de crédit",
"Credit limit saved": "Limite de crédit enregistrée",
"Type a number, for example 500.": "Tapez un nombre, par exemple 500.",
"No credit: pay on the spot": "Pas de crédit : paiement sur place",
"No warning signs.": "Aucun signe d'alerte.",
"Low risk": "Risque faible",
"Medium risk": "Risque moyen",
"High risk": "Risque élevé",
"Low": "Faible",
"Medium": "Moyen",
"High": "Élevé",
"Bad or No Credit": "Mauvais ou sans crédit",
"Credit": "Crédit",
"Days Overdue": "Jours de retard",
"Oldest Unpaid": "Plus ancien impayé",
"Total Billed": "Total facturé",
"Total Paid": "Total payé",
"Written Off": "Perdu",
"First Sale": "Première vente",
"Last Sale": "Dernière vente",
"Sales per Month": "Ventes par mois",
"Their Sales, Newest First": "Leurs ventes, les plus récentes d'abord",
"Customers appear here automatically when you add sales.": "Les clients apparaissent ici automatiquement quand vous ajoutez des ventes.",
"They may have been removed.": "Ils ont peut-être été supprimés.",
"Last Entry": "Dernière opération",
"Entries": "Opérations",
"No agent entries yet": "Pas encore d'opérations agents",
"Tap the green button to record a float transfer, EVC, bank exchange or other agent entry.": "Touchez le bouton vert pour noter un transfert de float, un EVC, un échange bancaire ou une autre opération agent.",
"Tap the green button to record your first sale.": "Touchez le bouton vert pour noter votre première vente.",
"Tap the green button to add one.": "Touchez le bouton vert pour en ajouter.",
"Message: Change Any Word Before Sending": "Message : changez ce que vous voulez avant l'envoi",
"Send on WhatsApp": "Envoyer sur WhatsApp",
"Start Over": "Recommencer",
"No phone number saved for them, so use Share or Copy.": "Pas de numéro enregistré, utilisez Partager ou Copier.",
"No one yet": "Personne pour l'instant",
"Press and hold the message to copy it.": "Appuyez longtemps sur le message pour le copier.",
"Press and hold the text to copy it.": "Appuyez longtemps sur le texte pour le copier.",
"Purchase": "Achat",
"Mobile Wallets": "Portefeuilles mobiles",
"By Month": "Par mois",
"Mobile Wallets, Net": "Portefeuilles mobiles, net",
"EVC, Net": "EVC, net",
"Total You Earned": "Total gagné",
"This Month": "Ce mois-ci",
"New Commission": "Nouvelle commission",
"Commission entries": "Commissions notées",
"One entry per wallet per month. Net is what you received, minus anything you shared with an Agent or Partner.": "Une ligne par portefeuille et par mois. Le net est ce que vous avez reçu, moins ce que vous avez partagé avec un agent ou un partenaire.",
"One row per purchase. You earn commission on the part you sell to customers (Retail). The part you sell on to other dealers (Wholesale) is passed on to them. If you share part of your commission with a partner or line owner, enter it in the form and it is taken off for you.": "Une ligne par achat. Vous gagnez une commission sur la part vendue aux clients (détail). La part revendue à d'autres revendeurs (gros) leur est reversée. Si vous partagez une partie de votre commission avec un partenaire ou le propriétaire de la ligne, indiquez-le dans le formulaire et elle est déduite pour vous.",
"Net, after partner and agent shares.": "Net, après les parts des partenaires et des agents.",
"Nothing yet. Add commission entries from the home screen, under Commissions.": "Rien pour l'instant. Ajoutez des commissions depuis l'accueil, dans Commissions.",
"Monthly totals appear here once you add wallet or EVC commissions.": "Les totaux mensuels apparaissent ici quand vous ajoutez des commissions de portefeuille ou EVC.",
"Deposit Rates": "Taux des dépôts",
"Flat deposit commission by amount. A deposit gets the commission of the highest \"From\" amount it reaches.": "Commission fixe sur les dépôts selon le montant. Un dépôt reçoit la commission du palier « Du » le plus élevé qu'il atteint.",
"Save rates": "Enregistrer les taux",
"Rates saved": "Taux enregistrés",
"For Data Sending and EVC, log one row per agent per day with that day's total. Log each Deposit on its own, because its commission depends on the amount.": "Pour l'envoi d'internet et l'EVC, notez une ligne par agent et par jour avec le total du jour. Notez chaque dépôt à part, car sa commission dépend du montant.",
"No referral sales yet": "Pas encore de ventes apporteurs",
"Payouts appear once you add referral sales.": "Les paiements apparaissent quand vous ajoutez des ventes apporteurs.",
"Worked out automatically from the sales, per agent per month.": "Calculé automatiquement à partir des ventes, par agent et par mois.",
"What to Pay": "Ce qu'il faut payer",
"Losses per month": "Pertes par mois",
"Total losses, all time": "Total des pertes, depuis le début",
"Write-offs on sales and agents, plus losses logged as errors": "Pertes sur les ventes et les agents, plus les pertes notées comme erreurs",
"No losses recorded.": "Aucune perte notée.",
"Error log": "Journal des erreurs",
"No errors logged.": "Aucune erreur notée.",
"To count an error as a loss, set \"Did it cost money?\" to Yes and fill in the amount.": "Pour compter une erreur comme une perte, mettez « Cela a-t-il coûté de l'argent ? » sur Oui et indiquez le montant.",
"Losses": "Pertes",
"Errors": "Erreurs",
"Main": "Principal",
"Changed to the new 9-digit number": "Changé pour le nouveau numéro à 9 chiffres",
"A 9-digit Gambian number starts with 83 (QCell), 86 (Comium) or 87 (Africell).": "Un numéro gambien à 9 chiffres commence par 83 (QCell), 86 (Comium) ou 87 (Africell).",
"Gambian numbers have 9 digits (starting 83, 86 or 87), or 7 digits for Gamcel (starting 9).": "Les numéros gambiens ont 9 chiffres (début 83, 86 ou 87), ou 7 chiffres pour Gamcel (début 9).",
"Check the number: it should have 6 to 13 digits without the country code.": "Vérifiez le numéro : il doit avoir 6 à 13 chiffres sans l'indicatif du pays.",
"Country code not recognised. Choose the country from the list instead.": "Indicatif de pays inconnu. Choisissez plutôt le pays dans la liste.",
"For Part Paid, the amount received must be more than 0 and less than the amount. If they paid it all, choose Paid in Full.": "Pour Payé en partie, le montant reçu doit être plus que 0 et moins que le montant. S'il a tout payé, choisissez Payé en entier.",
"Has more than 5 times their usual purchase to pay": "Doit plus de 5 fois son achat habituel",
"Has more than 3 times their usual purchase to pay": "Doit plus de 3 fois son achat habituel",
"Has more than their usual purchase to pay": "Doit plus que son achat habituel",
"No purchase for over 60 days but still has money to pay": "Aucun achat depuis plus de 60 jours mais doit encore de l'argent",
"Paid: settled. Overpaid: in credit. Outstanding: unpaid for up to 3 days. Overdue: unpaid for more than 3 days. Bad debt: written off.": "Payé : réglé. Payé en trop : en crédit. À payer : impayé depuis 3 jours au plus. En retard : impayé depuis plus de 3 jours. Créance perdue : passée en perte.",
"Regular means 3 or more sales and at least one a month.": "Régulier veut dire 3 ventes ou plus et au moins une par mois.",
"Regular: 3 or more sales and at least one a month. Irregular: fewer. Inactive: no sale for 90 days. Bad (high risk): oldest unpaid sale is over 60 days old. Do not give credit: something was written off.": "Régulier : 3 ventes ou plus et au moins une par mois. Irrégulier : moins. Inactif : aucune vente depuis 90 jours. Mauvais (risque élevé) : la plus vieille vente impayée a plus de 60 jours. Pas de crédit : une perte a été notée.",
"Points are added for: money unpaid for a long time, owing much more than their usual purchase, paying late before, and past write-offs. 60 points or more is High risk, 30 or more is Medium.": "Des points s'ajoutent pour : un impayé ancien, une dette bien plus grande que l'achat habituel, des retards passés et des pertes passées. 60 points ou plus : risque élevé ; 30 ou plus : moyen.",
"Since 4 September 2026, Africell numbers start with 87, QCell with 83 and Comium with 86. Gamcel numbers stay 7 digits. Type the old 7-digit number and the app adds the right start for you when you leave the box. Old and new forms of a number count as the same person.": "Depuis le 4 septembre 2026, les numéros Africell commencent par 87, QCell par 83 et Comium par 86. Les numéros Gamcel gardent 7 chiffres. Tapez l'ancien numéro à 7 chiffres et l'application ajoute le bon début en quittant la case. L'ancien et le nouveau numéro comptent comme la même personne.",
"Billed and Paid, Last 6 Months": "Facturé et payé, 6 derniers mois",
"Last 7 Days": "7 derniers jours",
"This Week": "Cette semaine",
"settled": "réglé",
"Nothing": "Rien",
"Billed and received by month": "Facturé et reçu par mois",
"Balances": "Soldes",
"New Entry": "Nouvelle opération",
"New Expense": "Nouvelle dépense",
"Nothing to pay yet": "Rien à payer pour l'instant",
"Paid by customers": "Payé par les clients",
"Paid through": "Payé par",
"Copy the rules": "Copier les règles",
"Connect": "Connecter",
"Online sync": "Synchronisation en ligne",
"In Chrome, open console.firebase.google.com, sign in with your Google account and create a project. You can switch Google Analytics off.": "Dans Chrome, ouvrez console.firebase.google.com, connectez-vous avec votre compte Google et créez un projet. Vous pouvez désactiver Google Analytics.",
"Open Authentication, tap Get started, choose Email/Password, switch it on and save.": "Ouvrez Authentication, touchez Get started, choisissez Email/Password, activez-le et enregistrez.",
"Open Firestore Database, tap Create database, pick a location near you and start in production mode.": "Ouvrez Firestore Database, touchez Create database, choisissez un lieu proche et démarrez en mode production.",
"In Firestore, open the Rules tab, replace everything with the rules below and tap Publish. They make sure only you can see your records.": "Dans Firestore, ouvrez l'onglet Rules, remplacez tout par les règles ci-dessous et touchez Publish. Elles garantissent que vous seul voyez vos données.",
"Open Project settings (the gear), scroll to Your apps, tap the web icon </>, give it a name and register it. Copy the whole firebaseConfig block it shows and paste it below.": "Ouvrez Project settings (la roue dentée), descendez jusqu'à Your apps, touchez l'icône web </>, donnez-lui un nom et enregistrez-la. Copiez tout le bloc firebaseConfig affiché et collez-le ci-dessous.",
"Once this is set up, every entry is saved to your own private online account automatically. No more backups, and you can sign in on another phone and see the same records.": "Une fois en place, chaque opération est enregistrée automatiquement dans votre compte privé en ligne. Plus besoin de sauvegardes, et vous pouvez vous connecter sur un autre téléphone et voir les mêmes données.",
"This app needs JavaScript turned on.": "Cette application a besoin de JavaScript.",
"Payment": "Paiement",
"Reminder": "Rappel",
"Reminders": "Rappels",
"Recent": "Récent",
"See all": "Tout voir",
"Tools": "Outils",
"Cash Check": "Caisse du jour",
"Monthly Check": "Contrôle mensuel",
"Capital": "Capital",
"Referrals": "Apporteurs",
"Reports": "Rapports",
"Tap New Sale to start.": "Touchez Nouvelle vente pour commencer.",
"Agents and advance payments": "Agents et paiements d'avance",
"Install the app": "Installer l'application",
"Install": "Installer",
"Opens like any app on your phone. Free and safe.": "S'ouvre comme toute autre application. Gratuit et sûr.",
"Tap the Share button, then Add to Home Screen.": "Touchez le bouton Partager, puis Sur l'écran d'accueil.",
"Install the App on This Phone": "Installer l'application sur ce téléphone",
"To install: tap the Share button, then Add to Home Screen.": "Pour installer : touchez Partager, puis Sur l'écran d'accueil.",
"Installing. The app will appear on your home screen.": "Installation. L'application apparaîtra sur votre écran d'accueil.",
"Installed. Open it from your home screen.": "Installée. Ouvrez-la depuis votre écran d'accueil."
},
 [
  [/^(\d+) customers$/, "$1 clients"],
  [/^(\d+) customers\. To collect: (.+)\. Paid in advance: (.+)\.$/, "$1 clients. À encaisser : $2. Payé d'avance : $3."],
  [/^(\d+) entries$/, "$1 opérations"],
  [/^1 entry$/, "1 opération"],
  [/^(\d+) entries, money in (.+)$/, "$1 opérations, entrées $2"],
  [/^1 entry, money in (.+)$/, "1 opération, entrées $1"],
  [/^(.+), (\d+) entries$/, "$t1, $2 opérations"],
  [/^(.+), 1 entry$/, "$t1, 1 opération"],
  [/^(\d+) recorded$/, "$1 notés"],
  [/^(\d+) sales, last (.+), oldest unpaid (\d+) days$/, "$1 ventes, dernière le $2, plus vieil impayé $3 jours"],
  [/^(\d+) sales, last (.+)$/, "$1 ventes, dernière le $2"],
  [/^1 sale, last (.+)$/, "1 vente, le $1"],
  [/^(\d+) sales, paid (.+)$/, "$1 ventes, payé $2"],
  [/^(.*\d.*) to collect$/, "$1 à encaisser"],
  [/^(.*\d.*) out$/, "$1 sorti"],
  [/^\(was (.+)\)$/, "(avant : $1)"],
  [/^\+(\d+) (.+)$/, "+$1 $t2"],
  [/^(.+) \(\+(\d+)\)$/, "$t1 (+$2)"],
  [/^A tip is on top of the bill\. It counts as extra income and is not used to pay the bill\. Example: bill (.+), customer pays (.+) and gives a tip of (.+)\.$/, "Le pourboire s'ajoute à la facture. Il compte comme revenu en plus et ne sert pas à payer la facture. Exemple : facture de $1, le client paie $2 et laisse $3 de pourboire."],
  [/^You type the total the customer paid, tip included\. The app takes the tip off before paying the bill\. Example: customer pays (.+) with a tip of (.+), so the bill gets (.+)\.$/, "Vous tapez le total payé par le client, pourboire compris. L'application retire le pourboire avant de payer la facture. Exemple : le client paie $1 avec $2 de pourboire, la facture reçoit donc $3."],
  [/^Example: (.+)$/, "Exemple : $1"],
  [/^After 1 minute$/, "Après 1 minute"],
  [/^After (\d+) minutes$/, "Après $1 minutes"],
  [/^Every (\d+) days$/, "Tous les $1 jours"],
  [/^Last (\d+) Days$/, "$1 derniers jours"],
  [/^All time (.+)$/, "Depuis le début : $1"],
  [/^This month\. All time (.+)$/, "Ce mois-ci. Depuis le début : $1"],
  [/^This month: billed (.+), paid (.+), tips (.+)\.$/, "Ce mois-ci : facturé $1, payé $2, pourboires $3."],
  [/^This month: billed (.+), paid (.+)\.$/, "Ce mois-ci : facturé $1, payé $2."],
  [/^Balances on (.+)$/, "Soldes du $1"],
  [/^Billed (.+?), paid (.+?), tip (.+?), paid (\d+) days late$/, "Facturé $1, payé $2, pourboire $3, payé avec $4 jours de retard"],
  [/^Billed (.+?), paid (.+?), paid (\d+) days late$/, "Facturé $1, payé $2, payé avec $3 jours de retard"],
  [/^Billed (.+?), paid (.+?), tip (.+)$/, "Facturé $1, payé $2, pourboire $3"],
  [/^Billed (.+?), paid (.+?), (\d+) days$/, "Facturé $1, payé $2, $3 jours"],
  [/^Billed (.+?), paid (.+)$/, "Facturé $1, payé $2"],
  [/^Paid to Agent (.*\d.*)$/, "Payé à l'agent $1"],
  [/^Received from Agent (.*\d.*)$/, "Reçu de l'agent $1"],
  [/^Paid (.*\d.*)$/, "Payé $1"],
  [/^(.+) \((.+)\), to collect (.+)$/, "$1 ($2), à encaisser $3"],
  [/^(.+) \((.+)\), paid in advance (.+)$/, "$1 ($2), payé d'avance $3"],
  [/^(.+), to collect (.*\d.*)$/, "$1, à encaisser $2"],
  [/^(.+), to pay (.*\d.*)$/, "$1, à payer $2"],
  [/^(.+), paid in advance (.*\d.*)$/, "$1, payé d'avance $2"],
  [/^(.+), settled$/, "$1, réglé"],
  [/^Bought (.+) \(retail (.+), wholesale (.+)\)\. You keep (.+), shared with partner (.+), passed to dealer (.+)$/, "Acheté $1 (détail $2, gros $3). Vous gardez $4, partagé avec le partenaire $5, reversé au revendeur $6"],
  [/^Bought (.+) \(retail (.+), wholesale (.+)\)\. You keep (.+), shared with partner (.+)$/, "Acheté $1 (détail $2, gros $3). Vous gardez $4, partagé avec le partenaire $5"],
  [/^Changed to the new (\d+)-digit number$/, "Changé pour le nouveau numéro à $1 chiffres"],
  [/^Counted (.+)$/, "Compté $1"],
  [/^Credit (.*\d.*)$/, "Crédit $1"],
  [/^Credit limit (.+) \(suggested\)$/, "Limite de crédit $1 (conseillée)"],
  [/^Credit limit (.+) \(set by you\)$/, "Limite de crédit $1 (fixée par vous)"],
  [/^Entry (\d+)$/, "Opération $1"],
  [/^Sale (\d+)$/, "Vente $1"],
  [/^(.+) paid (.+) in advance\. It is used on this sale automatically\. (.+) customer\.$/, "$1 a payé $2 d'avance. Ce montant est utilisé automatiquement pour cette vente. Client : $t3."],
  [/^(.+) still has (.+) to pay\. (.+) customer\.$/, "$1 doit encore $2. Client : $t3."],
  [/^(.+) has nothing to pay\. (.+) customer\.$/, "$1 n'a rien à payer. Client : $t2."],
  [/^Filled in from your last record on (.+)\. Change what has moved\.$/, "Rempli avec votre dernier relevé du $1. Changez ce qui a bougé."],
  [/^For your safety, the app asks for your password every (\d+) days\.$/, "Pour votre sécurité, l'application demande votre mot de passe tous les $1 jours."],
  [/^From (.*\d.*)$/, "Depuis le $1"],
  [/^Working Capital, from (.+)$/, "Capital de roulement, depuis le $1"],
  [/^You counted on (.+)$/, "Compté le $1"],
  [/^Highest: (.+)$/, "Maximum : $1"],
  [/^Last paid you (\d+) days ago$/, "Vous a payé il y a $1 jours"],
  [/^Has not paid you back in (\d+) days$/, "Ne vous a rien remboursé depuis $1 jours"],
  [/^Last used (.+)$/, "Utilisé le $1"],
  [/^Oldest unpaid sale is (\d+) days old$/, "La plus vieille vente impayée date de $1 jours"],
  [/^Has not paid for (\d+) days$/, "N'a pas payé depuis $1 jours"],
  [/^Had money written off before \((.+)\)$/, "A déjà eu une perte passée ($1)"],
  [/^Paid late 1 time$/, "A payé en retard 1 fois"],
  [/^Paid late (\d+) times$/, "A payé en retard $1 fois"],
  [/^Owes you (.+), which is (\d+)% of the (.+) that all agents owe you$/, "Vous doit $1, soit $2 % des $3 que tous les agents vous doivent"],
  [/^Too much depends on one customer: (.+) owes you (.+), which is (\d+)% of the (.+) that all customers owe you\. Think twice before giving them more credit\.$/, "Trop dépend d'un seul client : $1 vous doit $2, soit $3 % des $4 que tous les clients vous doivent. Réfléchissez avant de lui faire plus de crédit."],
  [/^1 high-risk customer has (.+) to pay$/, "1 client à risque élevé doit $1"],
  [/^(\d+) high-risk customers have (.+) to pay$/, "$1 clients à risque élevé doivent $2"],
  [/^1 customer is over their credit limit$/, "1 client dépasse sa limite de crédit"],
  [/^(\d+) customers are over their credit limit$/, "$1 clients dépassent leur limite de crédit"],
  [/^Money was missing on (\d+) checks? in the last 30 days \((.+) in total\)\. Open Daily Cash Check to see why\.$/, "Il manquait de l'argent à $1 contrôle(s) ces 30 derniers jours ($2 au total). Ouvrez le contrôle de caisse du jour pour voir pourquoi."],
  [/^(.+) has not paid you for (\d+) days and owes you (.+)$/, "$1 ne vous a pas payé depuis $2 jours et vous doit $3"],
  [/^Losses this month: (.+)$/, "Pertes ce mois-ci : $1"],
  [/^Over the credit limit by (.+)$/, "Dépasse la limite de crédit de $1"],
  [/^(.+) is high risk\. Ask for payment now instead of giving credit\. This goes over their credit limit of (.+)\. They would have (.+) to pay\.$/, "$1 est à risque élevé. Demandez le paiement maintenant au lieu de faire crédit. Cela dépasse sa limite de crédit de $2. Il devrait alors $3."],
  [/^(.+) is high risk\. Ask for payment now instead of giving credit\.$/, "$1 est à risque élevé. Demandez le paiement maintenant au lieu de faire crédit."],
  [/^This goes over their credit limit of (.+)\. They would have (.+) to pay\.$/, "Cela dépasse sa limite de crédit de $1. Il devrait alors $2."],
  [/^No Gambian network uses numbers starting with (\d)\. Africell: 2, 4 or 7\. QCell: 3 or 5\. Comium: 6 or 8\. Gamcel: 9\.$/, "Aucun réseau gambien n'a de numéros commençant par $1. Africell : 2, 4 ou 7. QCell : 3 ou 5. Comium : 6 ou 8. Gamcel : 9."],
  [/^(Africell|QCell|Comium) numbers start with (\d\d) and then (.+)\.$/, "Les numéros $1 commencent par $2 puis $3."],
  [/^Will be saved as (.+)$/, "Sera enregistré : $1"],
  [/^To Collect (.*\d.*)$/, "À encaisser $1"],
  [/^To Pay (.*\d.*)$/, "À payer $1"],
  [/^To collect (.*\d.*)$/, "À encaisser $1"],
  [/^to collect (.*\d.*)$/, "à encaisser $1"],
  [/^to pay (.*\d.*)$/, "à payer $1"],
  [/^To pay agents: (.+)$/, "À payer aux agents : $1"],
  [/^(.+) now: (.+)\. After this entry: (.+)\.$/, "$1 maintenant : $t2. Après cette opération : $t3."],
  [/^Still to pay (.+)$/, "Reste à payer $1"],
  [/^Nothing \(credit (.+)\)$/, "Rien (crédit $1)"],
  [/^Overpaid by (.+)$/, "Payé en trop de $1"],
  [/^Should have (.+), counted (.+)$/, "Devrait avoir $1, compté $2"],
  [/^Statement (.+), received (.+), shared with Agent or Partner (.+) \((.+)\)$/, "Relevé $1, reçu $2, partagé avec un agent ou partenaire $3 ($4)"],
  [/^Statement (.+), received (.+)$/, "Relevé $1, reçu $2"],
  [/^Show more \((\d+) older\)$/, "Voir plus ($1 plus anciens)"],
  [/^Reference (\S+)\. Recorded (.+?)\. Last changed (.+)\.$/, "Référence $1. Notée le $2. Modifiée le $3."],
  [/^Reference (\S+)\. Recorded (.+)\.$/, "Référence $1. Notée le $2."],
  [/^Reference (\S+)\.$/, "Référence $1."],
  [/^Save for (.+)$/, "Enregistrer ($1)"],
  [/^Saved (\d+) sales$/, "$1 ventes enregistrées"],
  [/^Saved 1 sale$/, "1 vente enregistrée"],
  [/^Saved (\d+) entrys?$/, "$1 opérations enregistrées"],
  [/^Saved (\d+) entries$/, "$1 opérations enregistrées"],
  [/^Saved\. (.+) is missing\. Open Daily Cash Check to see why\.$/, "Enregistré. Il manque $1. Ouvrez le contrôle de caisse du jour pour voir pourquoi."],
  [/^Saved\. (.+) extra\. Open Daily Cash Check to see why\.$/, "Enregistré. $1 en trop. Ouvrez le contrôle de caisse du jour pour voir pourquoi."],
  [/^Missing (.*\d.*)$/, "Manquant $1"],
  [/^Extra (.*\d.*)$/, "En trop $1"],
  [/^Welcome, (.+)$/, "Bienvenue, $1"],
  [/^Unpaid for over (\d+) days$/, "Impayé depuis plus de $1 jours"],
  [/^WhatsApp opens a chat with \+(\d+) with your message ready\. Nothing is sent until you press send there\.$/, "WhatsApp ouvre une discussion avec le +$1, avec votre message prêt. Rien n'est envoyé tant que vous n'appuyez pas sur Envoyer."],
  [/^Password reset email sent to (.+)\.$/, "E-mail pour changer le mot de passe envoyé à $1."],
  [/^Too many wrong tries\. Wait (\d+) seconds\.$/, "Trop d'essais incorrects. Attendez $1 secondes."],
  [/^(.+) added$/, "$1 ajouté"],
  [/^Credit limit for (.+), in (.+)\. Type 0 for no credit\.\nSuggested: (.+)\. Leave it empty to use the suggestion\.$/, "Limite de crédit pour $1, en $2. Tapez 0 pour aucun crédit.\nConseillé : $3. Laissez vide pour utiliser le conseil."],
  [/^How much did they pay now\? \((.+)\)$/, "Combien a-t-il payé maintenant ? ($1)"],
  [/^Restore this file\?\n\nIt has (\d+) sales and (\d+) agent entries\.\n\nIt will REPLACE everything currently in the app, and your online records too\.$/, "Restaurer ce fichier ?\n\nIl contient $1 ventes et $2 opérations agents.\n\nIl REMPLACERA tout ce qui est dans l'application, et aussi vos données en ligne."],
  [/^Restore this file\?\n\nIt has (\d+) sales and (\d+) agent entries\.\n\nIt will REPLACE everything currently in the app\.$/, "Restaurer ce fichier ?\n\nIl contient $1 ventes et $2 opérations agents.\n\nIl REMPLACERA tout ce qui est dans l'application."],
  [/^Fill in: (.+)\.$/, "À remplir : $l1."],
  [/^From \((.+)\)$/, "Du ($1)"],
  [/^To \((.+)\)$/, "Au ($1)"],
  [/^Commission \((.+)\)$/, "Commission ($1)"],
  [/^Phone language \((.+)\)$/, "Langue du téléphone ($1)"],
  [/^Paste the firebaseConfig block from step (\d)$/, "Collez le bloc firebaseConfig de l'étape $1"],
  [/^Security rules for step (\d)$/, "Règles de sécurité pour l'étape $1"],
  [/^Setup, about (\d+) minutes$/, "Installation, environ $1 minutes"],
  [/^Write Off as Bad Debt \((.+)\)$/, "Passer en perte ($1)"],
  [/^(\d+) customers? · (\d+) agents?$/, "$1 client(s) · $2 agent(s)"],
  [/^1 customer · (\d+) agents?$/, "1 client · $1 agent(s)"],
  [/^1 risk alert$/, "1 alerte de risque"],
  [/^(\d+) risk alerts$/, "$1 alertes de risque"],
  [/^(\d+) overdue$/, "$1 en retard"]
 ]);
I18N.add('fr', { "entries today": "saisies aujourd'hui", "entry today": "saisie aujourd'hui", "Unlock Agent & Client Tracker": "Déverrouiller Agent & Client Tracker", "Use PIN": "Utiliser le code" });
I18N.add('fr', { "Mobile Money": "Mobile money", "Banks": "Banques", "Microfinance": "Microfinance", "Other Ways": "Autres moyens", "Your Own": "Les vôtres", "Search": "Rechercher", "Which Bank?": "Quelle banque ?", "Which Microfinance?": "Quelle microfinance ?", "Banks and Microfinance": "Banques et microfinance" });
I18N.add('fr', { "Backup": "Sauvegarde", "Help": "Aide" });
I18N.add('fr', { "Already saved": "Déjà enregistrés" });
I18N.add('fr', { "All customers": "Tous les clients", "All agents": "Tous les agents", "Search name or number": "Chercher un nom ou un numéro", "No match. Close this and type the new name.": "Aucun résultat. Fermez et tapez le nouveau nom." });
I18N.add('fr', {
  "Message": "Message", "Record from a Message": "Enregistrer depuis un message", "Message from your wallet or bank": "Message de votre portefeuille ou banque",
  "Paste the SMS or notification here": "Collez le SMS ou la notification ici", "Paste the Copied Message": "Coller le message copié",
  "Copy the message in your SMS or wallet app, then tap Paste. You check the entry before it is saved.": "Copiez le message dans votre application SMS ou portefeuille, puis touchez Coller. Vous vérifiez la saisie avant qu'elle soit enregistrée.",
  "Money in": "Entrée d'argent", "Money out": "Sortie d'argent", "Check: in or out?": "À vérifier : entrée ou sortie ?", "No amount found. Type it in the entry.": "Aucun montant trouvé. Tapez-le dans la saisie.",
  "Number": "Numéro", "Name": "Nom", "Reference": "Référence", "Fee": "Frais", "Balance after": "Solde après", "When": "Quand", "Record it as": "L'enregistrer comme",
  "Payment of a Debt": "Paiement d'une dette", "New Sale, Paid": "Nouvelle vente, payée", "A customer paid for data, airtime or a deposit": "Un client a payé internet, crédit ou un dépôt",
  "A customer paying for an earlier sale": "Un client paie une vente précédente", "Received from an Agent": "Reçu d'un agent", "An agent sent you money or float": "Un agent vous a envoyé de l'argent ou du float",
  "Paid to an Agent": "Payé à un agent", "You sent money or float to an agent": "Vous avez envoyé de l'argent ou du float à un agent",
  "You sent money to a customer's wallet or bank": "Vous avez envoyé de l'argent au portefeuille ou à la banque d'un client", "Rent, transport, purchases or other spending": "Loyer, transport, achats ou autres dépenses",
  "Messages to Record": "Messages à enregistrer", "No payment messages are waiting.": "Aucun message de paiement en attente.", "Ignore": "Ignorer", "Record": "Enregistrer", "Ignore All": "Tout ignorer",
  "Ignore all waiting messages?": "Ignorer tous les messages en attente ?", "Check": "À vérifier", "Automatic Recording": "Enregistrement automatique", "Turn payment messages into entries": "Transformer les messages de paiement en saisies",
  "Read payment notifications": "Lire les notifications de paiement",
  "When a message from Wave, Afrimoney, QMoney, APS, your bank or your SMS app shows a payment, the app keeps it ready for you to record with one tap.": "Quand un message de Wave, Afrimoney, QMoney, APS, votre banque ou vos SMS indique un paiement, l'application le garde prêt à enregistrer en un geste.",
  "Change in Phone Settings": "Modifier dans les réglages du téléphone", "Turn On in Phone Settings": "Activer dans les réglages du téléphone",
  "Turn on Agent & Client Tracker in the page that opens.": "Activez Agent & Client Tracker dans la page qui s'ouvre.", "Android says \"Restricted setting\"?": "Android indique « Paramètre restreint » ?",
  "Tap Open App Info below, then the ⋮ menu at the top right, then Allow restricted settings. Come back and tap Turn On again.": "Touchez Infos de l'application ci-dessous, puis le menu ⋮ en haut à droite, puis Autoriser les paramètres restreints. Revenez et touchez Activer à nouveau.",
  "Open App Info": "Infos de l'application", "Alert me": "M'alerter", "Shows a notification when a payment message is ready to record, even when the app is closed.": "Affiche une notification quand un message de paiement est prêt à enregistrer, même si l'application est fermée.",
  "Turn Off Alerts": "Désactiver les alertes", "Turn On Alerts": "Activer les alertes", "Share a message to the app": "Partager un message vers l'application",
  "Press and hold a payment SMS or notification, tap Share, then choose Agent & Client Tracker. Or copy it and tap Message on the home screen.": "Appuyez longuement sur un SMS ou une notification de paiement, touchez Partager, puis choisissez Agent & Client Tracker. Ou copiez-le et touchez Message sur l'accueil.",
  "Fully automatic": "Entièrement automatique", "Reading payment notifications by itself needs the Android app.": "La lecture automatique des notifications nécessite l'application Android.",
  "Get the Android App": "Obtenir l'application Android", "Record from a Message Now": "Enregistrer depuis un message", "Press and hold the box, then tap Paste.": "Appuyez longuement sur la case, puis touchez Coller.",
  "Messages stay on this phone. Chats such as WhatsApp are never read. You always check an entry before it is saved.": "Les messages restent sur ce téléphone. Les discussions comme WhatsApp ne sont jamais lues. Vous vérifiez toujours une saisie avant son enregistrement."
}, [
  [/^(\d+) messages? to record$/, "$1 message(s) à enregistrer"], [/^Messages to Record \((\d+)\)$/, "Messages à enregistrer ($1)"],
  [/^(.+) is paying what they owe$/, "$1 paie ce qu'il doit"], [/^owes (.+)$/, "doit $1"]
]);
I18N.add('fr', {
  "Agent Phone": "Téléphone de l'agent", "Receiving Number": "Numéro qui a reçu", "Description (Optional)": "Description (facultatif)",
  "Assistant": "Assistant", "Master": "Principal", "Referral": "Apporteur", "Assistant Agent": "Agent assistant", "Referral Agent": "Agent apporteur", "EVC Agent": "Agent EVC",
  "Agent or Partner Phone": "Téléphone de l'agent ou du partenaire", "Type any name. New agents are welcome.": "Tapez n'importe quel nom. Les nouveaux agents sont acceptés.",
  "Overview": "Vue d'ensemble", "Bad Debt": "Créances irrécouvrables", "Bad Debt, All Time": "Créances irrécouvrables, au total", "No bad debt": "Aucune créance irrécouvrable",
  "When you write off money that will not be paid, it shows here with the customer or agent it belongs to.": "Quand vous passez en perte de l'argent qui ne sera pas payé, il apparaît ici avec le client ou l'agent concerné.",
  "Money written off as never to be paid. Tap a name to see their records.": "Argent passé en perte car il ne sera jamais payé. Touchez un nom pour voir ses saisies.",
  "Keep what you typed as a draft?": "Garder ce que vous avez tapé comme brouillon ?", "Continuing where you stopped": "Reprise là où vous vous êtes arrêté",
  "That entry no longer exists, so its draft was removed.": "Cette saisie n'existe plus, son brouillon a donc été supprimé.", "Drafts": "Brouillons", "No drafts.": "Aucun brouillon.",
  "Undo": "Annuler", "Undone": "Annulé", "Changes saved": "Modifications enregistrées", "Delete this entry?": "Supprimer cette saisie ?"
}, [
  [/^(\d+) drafts?$/, "$1 brouillon(s)"], [/^(\d+) write-offs?, last (.+)$/, "$1 perte(s), dernière le $2"], [/^1 person$/, "1 personne"], [/^(\d+) people$/, "$1 personnes"], [/^(\d+) rows$/, "$1 lignes"]
]);
I18N.add('fr', {
  "Date": "Date", "Time": "Heure", "Phone": "Téléphone", "Name": "Nom", "Details": "Détails", "Sent Out": "Envoyé", "Payment": "Paiement",
  "Received So Far": "Reçu jusqu'ici", "Your Cost": "Votre coût", "Date Paid": "Date du paiement", "Date for All Rows": "Date pour toutes les lignes",
  "Debt Payment": "Paiement de dette", "Edit Debt Payment": "Modifier le paiement de dette", "Debt Paid": "Dette payée",
  "Owed to Us": "On nous doit", "We Owe": "Nous devons", "Agents and advances": "Agents et avances", "Customers Owe Us": "Les clients nous doivent",
  "Owing": "Doivent", "Paid Ahead": "Payé d'avance", "Owes Now": "Doit maintenant", "After This": "Après ceci", "Fully paid": "Tout payé", "Paid": "Payé",
  "More info": "Plus d'infos", "More": "Plus", "Less": "Moins", "Owes us": "Nous doit", "Agent": "Agent",
  "No entries yet. Tap New Sale to start.": "Aucune saisie. Touchez Nouvelle vente pour commencer.",
  "This customer owes nothing. The money is kept as paid ahead.": "Ce client ne doit rien. L'argent est gardé comme payé d'avance.",
  "Customers and agents": "Clients et agents", "Sold to Dealers": "Vendu aux revendeurs", "Commission Rate (%)": "Taux de commission (%)",
  "Partner Share, Retail (%)": "Part du partenaire, détail (%)", "Partner Share, Wholesale (%)": "Part du partenaire, gros (%)", "1 entry": "1 saisie"
}, [
  [/^Owes Us (.+)$/, "Nous doit $1"], [/^Owes (.+)$/, "Doit $1"], [/^We Owe (.+)$/, "Nous devons $1"], [/^Paid Ahead (.+)$/, "Payé d'avance $1"],
  [/^Still owes (.+)$/, "Doit encore $1"], [/^Nothing, paid ahead (.+)$/, "Rien, payé d'avance $1"], [/^Agent owes us (.+)$/, "L'agent nous doit $1"],
  [/^We owe the agent (.+)$/, "Nous devons $1 à l'agent"], [/^Paid (.+)$/, "Payé $1"], [/^Received (.+)$/, "Reçu $1"], [/^Overdue$/, "En retard"],
  [/^(\d+) days$/, "$1 jours"], [/^(\d+) entries$/, "$1 saisies"],
  [/^(\d+) customers? · owing (.+) · paid ahead (.+)$/, "$1 client(s) · doivent $2 · payé d'avance $3"]
]);
